:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Activation Keys


[NOTE]
====
_Unit Cheat Scripts_
----
cheat-ak-create.sh
cheat-ak-attach-subs.sh
cheat-ak-autoenable.sh
----
====


[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official administration documentation.

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/content_management_guide/managing_activation_keys[Managing Activation Keys]
    
== Activation Keys Overview

Activation keys provide a means to easy system registration and subscription attachment. 

There are two methods to register a system with a Satellite Server:
   * authenticate with a Satellite Server using a username and password and then manually register a host, or
   * use an activation key (authentication token) to automate the process
      
== Create Activation Keys

.[root@satellite ~]$ 
----
hammer activation-key create \
--name "MyKey-DEV" \
--description "Development and early testing" \
--lifecycle-environment "MyLifecycle-DEV" \
--content-view "MyContent RHEL 7"  \
--organization "ExampleCom"
----

.[root@satellite ~]$ 
----
hammer activation-key create \
--name "MyKey-PROD" \
--description "Quality Assurance" \
--lifecycle-environment "MyLifecycle-PROD" \
--content-view "MyContent RHEL 7"  \
--organization "ExampleCom"
----

== Attach Subscriptions

First we need to identify available subscription IDs

.[root@satellite ~]$ 
----
hammer subscription list --organization "ExampleCom"
----

Same command with a different output format.

.[root@satellite ~]$ 
----
hammer --output base subscription list --organization "ExampleCom"
----

Take noice of the end date, quantity and consumed.  Each time an activation key is used, the consumed count increases.  When there are no subscriptions remaining, any attempt to use the key for host activation is rejected.

Now it's time to attach the subscriptions to the activation keys.  For our scenario, both DEV and PROD with consume the same subscription entitlement.

.[root@satellite ~]$ 
----
hammer activation-key add-subscription \
--name "desktop-dev" \
--subscription-id <ID-FROM-ABOVE-COMMAND> \
--organization "ExampleCom"

hammer activation-key add-subscription \
--name "desktop-prod" \
--subscription-id <ID-FROM-ABOVE-COMMAND> \
--organization "ExampleCom"
----

== Adjust Auto-Enable Status of Content

By default the Satellite-Tools content will not be enabled automatically when hosts register with an activation key.  This default bevahiour is easily overidden as follows:

.[root@satellite ~]$ 
----
hammer activation-key content-override \
--name "desktop-dev" \
--content-label rhel-7-server-satellite-tools-6.4-rpms \
--value 1 \
--organization "ExampleCom"

hammer activation-key content-override \
--name "desktop-prod" \
--content-label rhel-7-server-satellite-tools-6.4-rpms \
--value 1 \
--organization "ExampleCom"
----


== Additional Activities

.[root@satellite ~]$ 
----
hammer activation-key list --organization "ExampleCom"
----

.[root@satellite ~]$ 
----
hammer activation-key info --name "desktop-dev" --organization "ExampleCom"
----

[discrete]
== End of Unit

*Next:* link:Host-Management-Part1.adoc[Host Management Part 1]

link:../SAT6-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
