:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Activation Keys

.[root@workstation ~]$ 
----
whoami
----



[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official provisioning guide.

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/provisioning_guide/initialization_script_for_provisioning_examples[Provisioning Guide - Appendix A]


== Activation Keys Overview


== Create Activation Keys

.[root@workstation ~]$ 
----
hammer activation-key create \
--name "desktop-dev" \
--description "Desktops for development and early testing" \
--lifecycle-environment "Desktop-DEV" \
--content-view "Desktop-R7"  \
--organization "ExampleCom Test Lab"
----

.[root@workstation ~]$ 
----
hammer activation-key create \
--name "desktop-prob" \
--description "Desktops for development and early testing" \
--lifecycle-environment "Desktop-PROD" \
--content-view "Desktop-R7"  \
--organization "ExampleCom Test Lab"
----

== Attach Subscriptions

First we need to identify available subscription IDs

.[root@workstation ~]$ 
----
hammer subscription list --organization "ExampleCom Test Lab"
----

Same command with a different output format.

.[root@workstation ~]$ 
----
hammer --output base subscription list --organization "ExampleCom Test Lab"
----

Take noice of the end date, quantity and consumed.  Each time an activation key is used, the consumed count increases.  When there are no subscriptions remaining, any attempt to use the key for host activation is rejected.

Now it's time to attach the subscriptions to the activation keys.  For our scenario, both DEV and PROD with consume the same subscription entitlement.

.[root@workstation ~]$ 
----
hammer activation-key add-subscription \
--name "desktop-dev" \
--subscription-id <ID-FROM-ABOVE-COMMAND> \
--organization "ExampleCom Test Lab"

hammer activation-key add-subscription \
--name "desktop-prod" \
--subscription-id <ID-FROM-ABOVE-COMMAND> \
--organization "ExampleCom Test Lab"
----

== Adjust Auto-Enable Status of Content

By default the Satellite-Tools content will not be enabled automatically when hosts register with an activation key.  This default bevahiour is easily overidden as follows:

.[root@workstation ~]$ 
----
hammer activation-key content-override \
--name "desktop-dev" \
--content-label rhel-7-server-satellite-tools-6.4-rpms \
--value 1 \
--organization "ExampleCom Test Lab"

hammer activation-key content-override \
--name "desktop-prod" \
--content-label rhel-7-server-satellite-tools-6.4-rpms \
--value 1 \
--organization "ExampleCom Test Lab"
----

[discrete]
== End of Unit

*Next:* link:Host-Management.adoc[Host Management]

link:../SAT6-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
