:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Application Lifecycles

NOTE: This unit assumes you have successfully loaded a working manifest into the Red Hat Satellite Server.

NOTE: This unit also assume the 'hammer' command is configured correctly and functions without prompting for username and password.  If it does not, you may need to make some changes to the config file: _/root/.hammer/cli.modules.d/foreman.yml_

All the work in this unit will be performed on the satellite's command-line, or optionally in the WebUI.

If you have not already, connect to the satellite server.

.[root@workstation ~]$ 
----
ssh satellite
----

[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official provisioning guide.

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/provisioning_guide/initialization_script_for_provisioning_examples[Provisioning Guide - Appendix A]

== Create Lifecycle Environment

.[root@satellite ~]$ 
----
hammer lifecycle-environment create --name "Desktop-DEV" \
--description "Environment for Dekstop Active Development" \
--prior "Library" --organization "ExampleCom Test Lab"

hammer lifecycle-environment create --name "Desktop-QA" \
--description "Environment for Desktop Quality Assurance" \
--prior "Desktop-DEV" --organization "ExampleCom Test Lab"

hammer lifecycle-environment create --name "Desktop-PROD" \
--description "Environment for Desktop Production Releases" \
--prior "DeskTop-QA" --organization "ExampleCom Test Lab"
----

[discrete]
== End of Unit

*Next:* link:Content-Views.adoc[Content Views]

link:../SAT6-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
