:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Common Operator Tasks

Not sure just how common these tasks are, but as this workshop was built out we ran into things which needed to be managed.  So here is a pile of helpful tips and references.

== Start/Stop Satellite Services

A common question is "how do I restart the satellite service".  One can always reboot, but that is obviously not the ideal solution.

The proper way to manage the Satellite services is as follows:

.[root@satellite ~]$ 
----
katello-service stop
----

.[root@satellite ~]$ 
----
katello-service start
----

.[root@satellite ~]$ 
----
katello-service restart
----

== Check Satellite Services Status

.[root@satellite ~]$ 
----
hammer ping
----

== Logs to Watch

.[root@satellite ~]$ 
----
foreman-tail
----
 
== Cleaning up /var/spool/squid

.[root@satellite ~]$ 
----
katello-service stop

rm -rf /var/spool/squid/*

katello-service start
----

== Reset Admin Password

.[root@satellite ~]$ 
----
foreman-rake permissions:reset password=NewPassword
----

== Backups

Variants of the 'foreman-maintain backp' support:

  . *offline* - full offline backup. Satellite services are unavailable during the backup process
  . *online* - online backups are only for debugging purposes
  . *snashots* - snapshot method uses Logical Volume Manager (LVM) snapshots of the Pulp, MongoDB, and PostgreSQL directories. The backup is then created from the LVM snapshots and not from the running Satellite

Refer to the documentation:

link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4-beta/html/administering_red_hat_satellite/chap-red_hat_satellite-administering_red_hat_satellite-backup_and_disaster_recovery[Backup and Disaster Recovery]

[discrete]
== End of Unit

link:../SAT6-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
