:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Content Synchronization

NOTE: This unit assumes you have successfully loaded a working manifest into the Red Hat Satellite Server.

NOTE: This unit also assume the 'hammer' command is configured correctly and functions without prompting for username and password.  If it does not, you may need to make some changes to the config file: _/root/.hammer/cli.modules.d/foreman.yml_

All the work in this unit will be performed on the satellite's command-line, or optionally in the WebUI.

If you have not already, connect to the satellite server.

.[root@workstation ~]$ 
----
ssh satellite
----

On the satellite server, for those not interested in typing there are cheat-scripts available to execute all the tasks within this unit.  Please do take the time to review the commands and their parameters if you oopt to invoke the scripts.

[NOTE]
====
_Unit Cheat Script_
----
cheat-enable-repos.sh
cheat-set-policy.sh
cheat-sync-repos.sh
----
====


[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official provisioning guide.

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/provisioning_guide/initialization_script_for_provisioning_examples[Provisioning Guide - Appendix A]

== Enable Repos

The most difficult part of getting all of the parameters right is figuring out the exact 'name'.  The following command helped me out a great deal.  If you find something better, let me know: 'hammer repository-set list --product "Red Hat Enterprise Linux Server" --organization "ExampleCom Test Lab"'

.[root@workstation ~]$ 
----
hammer repository-set enable \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--basearch "x86_64" \
--releasever "7Server" \
--name "Red Hat Enterprise Linux 7 Server (RPMs)"
----

.[root@workstation ~]$ 
----
hammer repository-set enable \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--basearch "x86_64" \
--releasever "7Server" \
--name "Red Hat Enterprise Linux 7 Server - Optional (RPMs)"
----

.[root@workstation ~]$ 
----
hammer repository-set enable \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--basearch "x86_64" \
--name "Red Hat Enterprise Linux 7 Server - Extras (RPMs)"
----

.[root@workstation ~]$ 
----
hammer repository-set enable \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--basearch "x86_64" \
--releasever "7.5" \
--name "Red Hat Enterprise Linux 7 Server (Kickstart)"
----

.[root@workstation ~]$ 
----
hammer repository-set enable \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--basearch "x86_64" \
--name "Red Hat Satellite Tools 6.4 (for RHEL 7 Server) (RPMs)"
----

== Change Download Policy

Notice that the names are not identical below.  They appear to include the base architecture and release version in the name.  You can get the list of names using 'hammer repository list'.


.[root@workstation ~]$ 
----
hammer repository update  \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--name "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server" \
--download-policy immediate
----

.[root@workstation ~]$ 
----
hammer repository update \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--name "Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server" \
--download-policy immediate
----

.[root@workstation ~]$ 
----
hammer repository update \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--name "Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64" \
--download-policy immediate
----

.[root@workstation ~]$ 
----
hammer repository update \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--name "Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.5" \
--download-policy immediate
----

.[root@workstation ~]$ 
----
hammer repository update \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--name "Red Hat Satellite Tools 6.4 for RHEL 7 Server RPMs x86_64" \
--download-policy immediate
----

== Synchronize Repos

Since all of the content we are currently working with falls under a single product category, we can specify to sync all of it simultaneously.

.[root@workstation ~]$ 
----
hammer product synchronize \
--organization "ExampleCom" \
--name "Red Hat Enterprise Linux Server" \
--async
----


[discrete]
== End of Unit

*Next:* link:App-Lifecycles.adoc[Application Lifecycles]

link:../SAT6-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
