:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Content Synchronization

WARNING: This unit assumes you have successfully loaded a working manifest into the Red Hat Satellite Server.

WARNING: This unit also assumes the 'hammer' command is configured correctly and functions without prompting for username and password.  If it does not, you may need to make some changes to the config file: _/root/.hammer/cli.modules.d/foreman.yml_

All the work in this unit will be performed on the satellite's command-line, or optionally in the WebUI.

If you have not already, connect to the satellite server.

.[root@workstation ~]$ 
----
ssh satellite
----

On the satellite server, for those not interested in typing there are cheat-scripts available to execute all the tasks within this unit.  Please do take the time to review the commands and their parameters if you oopt to invoke the scripts.

[NOTE]
====
_Unit Cheat Script_
----
cheat-repos-enable.sh
cheat-repos-policy.sh
cheat-repos-sync.sh
----
====


[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official provisioning guide.

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/provisioning_guide/initialization_script_for_provisioning_examples[Provisioning Guide - Appendix A]

== Enable Repos

The most difficult part of getting all of the parameters right is figuring out the exact 'name'.  The following commands helped me out a great deal.  If you find something better, let me know: 

.[root@satellite ~]$
----
hammer repository-set list --product "Red Hat Enterprise Linux Server" --organization "ExampleCom"

hammer product list --organization "ExampleCom"
----

Once you have the names, you can begin to enable the desired repos.

.[root@satellite ~]$ 
----
hammer repository-set enable \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--basearch "x86_64" \
--releasever "7Server" \
--name "Red Hat Enterprise Linux 7 Server (RPMs)"
----

.[root@satellite ~]$ 
----
hammer repository-set enable \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--basearch "x86_64" \
--releasever "7Server" \
--name "Red Hat Enterprise Linux 7 Server - Optional (RPMs)"
----

.[root@satellite ~]$ 
----
hammer repository-set enable \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--basearch "x86_64" \
--releasever "7.6" \
--name "Red Hat Enterprise Linux 7 Server (Kickstart)"
----

.[root@satellite ~]$ 
----
hammer repository-set enable \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--basearch "x86_64" \
--name "Red Hat Satellite Tools 6.6 (for RHEL 7 Server) (RPMs)"
----

== Change Download Policy

Notice that the names are not identical below.  They appear to include the base architecture and release version in the name.  You can get the list of names using 'hammer repository list'.


.[root@satellite ~]$ 
----
hammer repository update  \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--name "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server" \
--download-policy immediate
----

.[root@satellite ~]$ 
----
hammer repository update \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--name "Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server" \
--download-policy immediate
----

.[root@satellite ~]$ 
----
hammer repository update \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--name "Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.6" \
--download-policy immediate
----

.[root@satellite ~]$ 
----
hammer repository update \
--organization "ExampleCom" \
--product "Red Hat Enterprise Linux Server" \
--name "Red Hat Satellite Tools 6.6 for RHEL 7 Server RPMs x86_64" \
--download-policy immediate
----

== View Current Enabled Repositories

Before starting the synchronization process, it might be wise to do a quick sanity check.

.[root@satellite ~]$ 
----
hammer repository list --organization "ExampleCom"
----

== Synchronize Repos

Since all of the content we are currently working with falls under a single product category, we can specify to sync all of it simultaneously.

.[root@satellite ~]$ 
----
hammer product synchronize \
--organization "ExampleCom" \
--name "Red Hat Enterprise Linux Server" \
--async
----

== Synchonization Status

You can inspect the synchronization status with following command.  Unfortunately you need a really wide terminal for easy viewing, but the information is there.

.[root@satellite ~]$ 
----
hammer product list --enabled true --organization ExampleCom
----

----
----|---------------------------------|-------------|--------------|--------------|-----------
ID  | NAME                            | DESCRIPTION | ORGANIZATION | REPOSITORIES | SYNC STATE
----|---------------------------------|-------------|--------------|--------------|-----------
122 | Red Hat Enterprise Linux Server |             | ExampleCom   | 4            | Running  
----|---------------------------------|-------------|--------------|--------------|-----------
----

For a more detailed report per respository, first identify the correct ID.

.[root@satellite ~]$ 
----
hammer repository list --organization "ExampleCom"
----

----
---|------------------------------------------------------------------|---------------------------------|--------------|---------------------------------------------------------------------------------
ID | NAME                                                             | PRODUCT                         | CONTENT TYPE | URL
---|------------------------------------------------------------------|---------------------------------|--------------|---------------------------------------------------------------------------------
3  | Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.5           | Red Hat Enterprise Linux Server | yum          | https://cdn.redhat.com/content/dist/rhel/server/7/7.5/x86_64/kickstart
2  | Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server | Red Hat Enterprise Linux Server | yum          | https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/optional/os
1  | Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server            | Red Hat Enterprise Linux Server | yum          | https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os
4  | Red Hat Satellite Tools 6.6 for RHEL 7 Server RPMs x86_64        | Red Hat Enterprise Linux Server | yum          | https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/sat-tools/6....
---|------------------------------------------------------------------|---------------------------------|--------------|---------------------------------------------------------------------------------
----

Then fetch the current information

.[root@satellite ~]$ 
----
hammer repository info --id=1  --organization "ExampleCom"
----

----
ID:                 1
Name:               Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server
Label:              Red_Hat_Enterprise_Linux_7_Server_RPMs_x86_64_7Server
Organization:       ExampleCom
Red Hat Repository: yes
Content Type:       yum
Mirror on Sync:     yes
URL:                https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os
Publish Via HTTP:   no
Published At:       https://satellite.sat6.example.com/pulp/repos/ExampleCom/Library/content/dist/rhel/server/7/7Server/x86_64/os/
Relative Path:      ExampleCom/Library/content/dist/rhel/server/7/7Server/x86_64/os
Download Policy:    immediate
Product:
    ID:   122
    Name: Red Hat Enterprise Linux Server
GPG Key:

Sync:
    Status:
Created:            2020/05/30 04:52:08
Updated:            2020/05/30 04:52:33
Content Counts:
    Packages:       9382
    Source RPMS:    0
    Package Groups: 76
    Errata:         4360
    Module Streams: 0
----

NOTE: When a product have been successfully sync'd, it will show a `Last Sync Date:` with a date and/or time value.

[discrete]
== End of Unit

link:../SAT6-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
