:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Content Views

NOTE: This unit assumes you have successfully loaded a working manifest into the Red Hat Satellite Server.

NOTE: This unit also assume the 'hammer' command is configured correctly and functions without prompting for username and password.  If it does not, you may need to make some changes to the config file: _/root/.hammer/cli.modules.d/foreman.yml_

All the work in this unit will be performed on the satellite's command-line, or optionally in the WebUI.

If you have not already, connect to the satellite server.

.[root@workstation ~]$ 
----
ssh satellite
----

On the satellite server, for those not interested in typing there is a cheat-script available to execute all the tasks within this unit.  Please do take the time to review the commands and their parameters if you opt to invoke the script.

[NOTE]
====
_Unit Cheat Script_
----
cheat-cv-create.sh
cheat-cv-publish.sh
cheat-cv-promote.sh
----
====


[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official provisioning guide.

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/provisioning_guide/initialization_script_for_provisioning_examples[Provisioning Guide - Appendix A]

== List Repository IDs

.[root@satellite ~]$ 
----
#  hammer repository list --organization "ExampleCom"
----

.Command Output
[source,indent=4]
----
ID | NAME                                                             | PRODUCT                         | CONTENT TYPE | URL            
3  | Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.5           | Red Hat Enterprise Linux Server | yum          | https://cdn.redhat.com/content/dist/rhel/server/7/7.5/x86_64/kickstart
2  | Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server | Red Hat Enterprise Linux Server | yum          | https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/optional/os
1  | Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server            | Red Hat Enterprise Linux Server | yum          | https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os
4  | Red Hat Satellite Tools 6.4 for RHEL 7 Server RPMs x86_64        | Red Hat Enterprise Linux Server | yum          | https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/sat-tools/6....
----


== Create a Content View

.[root@satellite ~]$ 
----
# Create and publish our Content View
hammer content-view create --name "MyContent RHEL 7" \
--description "RHEL 7 OS Content" \
--repository-ids 2,1,4 \
--organization "ExampleCom"
----

== Publish the Content View

.[root@satellite ~]$ 
----
hammer content-view publish --name "MyContent RHEL 7" \
--description "Initial content view publication" \
--organization "ExampleCom"
----

== Promote the Content View

.[root@satellite ~]$ 
----
hammer content-view version promote \
--content-view "MyContent RHEL 7" \
--version 1 \
--to-lifecycle-environment "MyLifecycle-DEV" \
--organization "ExampleCom"

hammer content-view version promote \
--content-view "MyContent RHEL 7" \
--version 1 \
--to-lifecycle-environment "MyLifecycle-QA" \
--organization "ExampleCom"

hammer content-view version promote \
--content-view "MyContent RHEL 7" \
--version 1 \
--to-lifecycle-environment "MyLifecycle-PROD" \
--organization "ExampleCom"

----

== List Content Views

.[root@satellite ~]$ 
----
hammer content-view list
----

----
----------------|---------------------------|---------------------------|-----------|---------------------|---------------
CONTENT VIEW ID | NAME                      | LABEL                     | COMPOSITE | LAST PUBLISHED      | REPOSITORY IDS
----------------|---------------------------|---------------------------|-----------|---------------------|---------------
1               | Default Organization View | Default_Organization_View |           | 2020/05/30 04:38:05 |
2               | MyContent RHEL 7          | MyContent_RHEL_7          |           | 2020/05/30 13:41:36 | 4, 1
----------------|---------------------------|---------------------------|-----------|---------------------|---------------
----

[discrete]
== End of Unit

link:../SAT6-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
