:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Content Views

NOTE: This unit assumes you have successfully loaded a working manifest into the Red Hat Satellite Server.

NOTE: This unit also assume the 'hammer' command is configured correctly and functions without prompting for username and password.  If it does not, you may need to make some changes to the config file: _/root/.hammer/cli.modules.d/foreman.yml_

All the work in this unit will be performed on the satellite's command-line, or optionally in the WebUI.

If you have not already, connect to the satellite server.

.[root@workstation ~]$ 
----
ssh satellite
----

On the satellite server, for those not interested in typing there is a cheat-script available to execute all the tasks within this unit.  Please do take the time to review the commands and their parameters if you oopt to invoke the script.

[NOTE]
====
_Unit Cheat Script_
----
cheat-content-views.sh
----
====


[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official provisioning guide.

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/provisioning_guide/initialization_script_for_provisioning_examples[Provisioning Guide - Appendix A]

== Create a Content View

.[root@satellite ~]$ 
----
# Create and publish our Content View
hammer content-view create --name "Desktop-R7" \
--description "Desktop RHEL 7 OS" \
--product "Red Hat Enterprise Linux Server" \
--repositories "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server,Red Hat Satellite Tools 6.4 for RHEL 7 Server RPMs x86_64" \
--organization "ExampleCom"
----

== Publish the Content View

.[root@satellite ~]$ 
----
hammer content-view publish --name "Desktop-R7" \
--description "Initial content view for our operating system" \
--organization "ExampleCom"
----

== Promote the Content View

.[root@satellite ~]$ 
----
hammer content-view version promote \
--content-view "Desktop-R7" \
--version 1 \
--to-lifecycle-environment "Desktop-DEV" \
--organization "ExampleCom"

hammer content-view version promote \
--content-view "Desktop-R7" \
--version 1 \
--to-lifecycle-environment "Desktop-QA" \
--organization "ExampleCom"

hammer content-view version promote \
--content-view "Desktop-R7" \
--version 1 \
--to-lifecycle-environment "Desktop-PROD" \
--organization "ExampleCom"

----


[discrete]
== End of Unit

*Next:* link:Host-Groups.adoc[Host Groups]

link:../SAT6-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
