:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Getting Started

[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Red Hat's official documentation can be found publicly with the links provided below.  It is important to note that this workshop guide supports a very narrowly scoped and simple installation of the Openshift Container Platform (OCP).  Please refer to the official Red Hat documentation for complete information on the installation procedures.


    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/[Satellite 6.4 Documentation]

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/planning_for_red_hat_satellite_6/[Satellite 6.4 Planning Guide]
   
   * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/quick_start_guide/[Satellite 6.4 Quick Start Guide]


With that said, the steps of preparing and installing Satellite in this workshop environment have been condensed into 3 scripts which execute a set of Ansible Playbooks.  Please follow the steps below to begin your installation of the Openshift Container Platform.

== Satellite Pre Installation

=== Sign-On on to your *workstation* session

Using the connection information and credentials provided by the instructor, get yourselves signed into your workstation session.

=== Enable 'screen' Terminal Session

Again, if you haven't already we stronlgy encourage the use of the `screen` utility.
    
.[student@workstation ~]$ 
----
screen -m
----

For more tips on using screen have a look in the link:./Preface.adoc[Workshop Preface]

=== Become the root user

In order to execute the pre-installation steps, we need to become the administrative user 'root'

.[student@workstation ~]$ 
----
sudo -i
----

=== Download the Workshop project from GitHub

.[root@workstation ~]#
----
cd ~
    
git clone https://github.com/xtophd/SAT6-Workshop
----

=== Run the pre-install script

WARNING: It is important to be in the correct working directory for these installation procedures to function properly.  

.[root@workstation ~]#
----
cd ~/SAT6-Workshop
----

Now you are ready to proceed with executing the pre-install steps.  This typically runs for about 3-5 minutes.    

.[root@workstation OCP-Workshop]#
----
bash 01-pre-install-script.sh
----


.[root@workstation OCP-Workshop]# - THINGS I NEED TO PUT IN PLAYBOOKS
----
Create RHEL 7 from template

## PLAYBOOK SHOULD HAVE VARIABLE TO IDENTIFY WHICH DISK / VOLUME TO USE

Added 200 GB disk
Created 200 GB sat64vg volume group

fdisk /dev/vdb

# Create LVM - USE SSM TO DO ALL THIS WORK
pvcreate /dev/vdb1
vgcreate vg_sat /dev/vdb1
lvcreate -L 50GB -n mongodb vg_sat
lvcreate -L 100GB -n pulp vg_sat
lvcreate -L 5GB -n pgsql vg_sat
lvcreate -L 5GB -n squid vg_sat
lvcreate -L 20GB -n cache vg_sat

#Created xfs filesystems
mkfs -t xfs /dev/vg_sat/mongodb
mkfs -t xfs /dev/vg_sat/pulp
mkfs -t xfs /dev/vg_sat/pgsql
mkfs -t xfs /dev/vg_sat/squid
mkfs -t xfs /dev/vg_sat/cache

#Created Mount point in fstab
/dev/mapper/vg_sat-pulp      /var/lib/pulp     xfs     defaults        0 0
/dev/mapper/vg_sat-pgsql     /var/lib/pgsql    xfs     defaults        0 0
/dev/mapper/vg_sat-mongodb   /var/lib/mongodb  xfs     defaults        0 0
/dev/mapper/vg_sat-squid     /var/spool/squid  xfs     defaults        0 0
/dev/mapper/vg_sat-cache     /var/cache        xfs     defaults        0 0

## We are going to create a new /var/cache
mv /var/cache /var/cache.old

#Create Mount Points
mkdir -p /var/lib/{pulp,pgsql,mongodb} /var/spool/squid /var/cache

## Mount everything
mount -a

## Restore cache directory contents
cd /var/cache
tar cf - -C /var/cache.old . | tar xvpf -

## Remove old cache directory
rm -rf /var/cache.old

# If registered, unregister
subscription-manager unregister
subscription-manager clean

## This is only required until I update the blueprint (If I chose to use RedHat CND on not local repos)
# Restore rhsm.conf from original
cp /etc/rhsm/rhsm.conf.rpmnew /etc/rhsm/rhsm.conf

# Subscription Manager Register
subscription-manager register
subscription-manager remove --all
subscription-manager list --available
subscription-manager attach --pool=<>

# Subscription manager disable repos
subscription-manager repos --disable=*

# Subscribe to repos
subscription-manager repos --enable=rhel-7-server-rpms \
--enable=rhel-server-rhscl-7-rpms \
--enable=rhel-7-server-satellite-6.4-rpms \
--enable=rhel-7-server-satellite-maintenance-6-rpms \
--enable=rhel-7-server-ansible-2.6-rpms

# Ensure sub manager not locked into specific release of RHEL
subscription-manager release --unset

# Clean yum cache, etc
yum clean all

# Update box
yum update -y

# If host is on RHV virtulization platform
subscription-manager repos --enable=rhel-7-server-rh-common-rpms
yum install rhevm-guest-agent-common
subscription-manager repos --disable=rhel-7-server-rh-common-rpms

# other tools I like
yum install bind-utils,screen

#check selinux policy
getenforce

# start and enable firewalld
systemctl start firewalld
systemctl enable firewalld

# firewall rules

firewall-cmd --add-port="53/udp" --add-port="53/tcp" \
--add-port="67/udp" --add-port="69/udp" \
--add-port="80/tcp" --add-port="443/tcp" \
--add-port="5000/tcp" --add-port="5647/tcp" \
--add-port="8000/tcp" --add-port="8140/tcp" \
--add-port="9090/tcp"

firewall-cmd --runtime-to-permanent

##
## REBOOT
##
systemctl reboot

##
## RPM Installation - satellite
##
yum install -y satellite 

## RPM Installation - sos
yum install -y sos

## RPM Installation - discovery tools
yum install -y foreman-discovery-image

##
## SATELLITE Installation
##
satellite-installer --scenario satellite \
--foreman-initial-organization "Linuxsoup Test Lab" \
--foreman-initial-location "Irving, Tx" \
--foreman-admin-username admin \
--foreman-admin-password redhat \
--foreman-proxy-dns-managed=false \
--foreman-proxy-dhcp-managed=false

## Log on to Red Hat Access Portal
## Create manifest
Subscriptions->Subscription Allocation->Red Hat Satellite

## Log on to WebUI (admin/redhat)
## Manifest Import
Content->Subscriptions / Manage Manifest
Import Manifest

##
## DONE!!!
##
----


== Conclusion

The installation of Red Hat Satellite is now complete and you should be ready to begin with the exercises.  A couple of remaining words of advice:

1.  Some exercises are dependant on the successful completion of other exericses.  Those dependencies will be noted at the top of each unit.
2.  Pay attention to which linux login to use
3.  Pay attention to which satellite user to use
4.  Also be sure to pay close attention to which host you are executing tasks from

[discrete]
== End of Unit

*Next:* link:PXE-Less-Discovery.adoc[Provisioning with PXE-less Discovery]

link:../SAT6-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
