:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Getting Started

[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Red Hat's official documentation can be found publicly with the links provided below.  It is important to note that this workshop guide supports a very narrowly scoped and simple installation of the Openshift Container Platform (OCP).  Please refer to the official Red Hat documentation for complete information on the installation procedures.


    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.3/[Satellite 6.4 Documentation]

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.3/html/planning_for_red_hat_satellite_6/[Satellite 6.3 Planning Guide]
   
   * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.3/html/quick_start_guide/[Satellite 6.3 Quick Start Guide]

   * link:https://access.redhat.com/articles/2258471[Hammer cheat-sheat]

With that said, the steps of preparing and installing Satellite in this workshop environment have been condensed into 3 scripts which execute a set of Ansible Playbooks.  Please follow the steps below to begin your installation of the Openshift Container Platform.

== Satellite Pre Installation

=== Sign-On on to your *workstation* session

Using the connection information and credentials provided by the instructor, get yourselves signed into your workstation session.

=== Enable 'screen' Terminal Session

Again, if you haven't already we stronlgy encourage the use of the `screen` utility.
    
.[student@workstation ~]$ 
----
screen -m
----

For more tips on using screen have a look in the link:./Preface.adoc[Workshop Preface]

=== Become the root user

In order to execute the pre-installation steps, we need to become the administrative user 'root'

.[student@workstation ~]$ 
----
sudo -i
----

=== Download the Workshop project from GitHub

.[root@workstation ~]#
----
cd ~
    
git clone https://github.com/xtophd/SAT6-Workshop
----

=== Run the installaction script

WARNING: It is important to be in the correct working directory for these installation procedures to function properly.  

.[root@workstation ~]#
----
cd ~/SAT6-Workshop
----

Subscript to correct content

.[root@workstation ~]#
----
subscription-manager repos \
--enable rhel-7-server-rpms \
--enable rhel-server-rhscl-7-rpms \
--enable rhel-7-server-satellite-6.3-rpms
----


Now you are ready to proceed with executing the pre-install steps.  This typically runs for about 35-40 minutes.    

.[root@workstation OCP-Workshop]#
----
bash install-satellite.sh
----

=== Procure Satellite Manifest

While you are waiting on the installation to complete, you can procure your satellite manifest.

NOTE: For this workshop you will be provided with a working manifest by the instructor.  Following instructions are informational

Creating and downloading a Satellite Manifest is done by visiting the link:https://access.redhat.com/[Red Hat Customer Portal], sign-on with your credentials and then proceeding to link:https://access.redhat.com/management/[My Subscriptions].

Next proceed to link:https://access.redhat.com/management/subscription_allocations[Subscription Allocations].

Now click on link:https://access.redhat.com/management/subscription_allocations/new[New Subscription Allocations].

Give it a Name: example.com
Type: Satellite 6.4

Click Create

Add Subscriptions to the Subscription Allocation

Download Manifest.

=== Load the Manifest

Using your Browser, proceed to sign-on to your Satellite server.

Go to "Subscriptions"

Upload your Manifest

This process will takes a few minutes.

At this point the Satellite is ready for use.

NOTE: You can load manifest from cli with: hammer subscription upload --file manifest.zip --organization "ExampleCom Test Lab"

== Conclusion

The installation of Red Hat Satellite is now complete and you should be ready to begin with the exercises.  A couple of remaining words of advice:

1.  Some exercises are dependant on the successful completion of other exericses.  Those dependencies will be noted at the top of each unit.
2.  Pay attention to which linux login to use
3.  Pay attention to which satellite user to use
4.  Also be sure to pay close attention to which host you are executing tasks from

[discrete]
== End of Unit

link:../SAT6-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
