:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Host Groups

.[root@workstation ~]$ 
----
whoami
----

[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official provisioning guide.

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/provisioning_guide/initialization_script_for_provisioning_examples[Provisioning Guide - Appendix A]


== Host Group Overview

A host group is in some ways similar to an inherited node declaration, in that it is a high level grouping of classes that can be named and treated as a unit. This is then treated as a template and is selectable during the creation of a new host and ensures that the host is configured in one of your pre-defined states. In addition to defining which puppet classes get included when building this host type you are also able to assign variables and provisioning information to a host group to further refine the behavior of the puppet runtime. The host group's classes and the host group's variables are included in the external node information when the puppetmaster compiles the host's configuration.

[discrete]
== End of Unit

link:../SAT6-Workshop.adoc#poc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
