:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Fundamental Host Management & Patching

[NOTE]
====
_Unit Cheat Scripts_
----
cheat-register-host.sh
----
====


[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official provisioning guide.

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/managing_hosts/[Managing Hosts]

== Overview of Host Management

A host is defined as any Red Hat Enterprise Linux system that Red Hat Satellite manages, physical or virtual. Virtual hosts may be deployed on any platform supported by Red Hat Satellite (ex: KVM, VMware vSphere, OpenStack, Amazon EC2, Rackspace Cloud Services, Google Compute Engine)

Red Hat Satellite enables host management at scale, including:
   * monitoring, 
   * provisioning, 
   * remote execution, 
   * configuration management, 
   * software management, and 
   * subscription management. 
   
Hosts can be managed through the Red Hat Satellite web UI or through command line tools like 'hammer'.

Once a host is entitled with a subscription, we refer to it as a 'Content Host'.

== Registration

.[root@node1 ~]$ 
----
subscription-manager register --serverurl=satellite.example.com  --org="ExampleCom" --activationkey="desktop-dev"
----

== Inspect Enabled Repos

.[root@node1 ~]$ 
----
subscription-manager repos
----

== Install Satellite Client Agent

.[root@node1 ~]$ 
----
yum install katello-agent
----

== Upload Package Info

.[root@node1 ~]$ 
----
katello-package-upload
----

== Audit

At this point, switch to using the Satellite WebUI.

Go to 'Hosts -> All Hosts'
Select 'node1'

Expore the tabs for Facts, Content and Errata.

== Remediation

Once you are in the Errata tab for 'node1', select all errata and apply.

Host has now been patched.

[discrete]
== End of Unit

*Next:* link:Host-Groups.adoc[Host Groups]

link:../SAT6-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
