:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Fundamental Host Management: Registration & Patching

NOTE: This unit assumes you have successfully loaded a working manifest into the Red Hat Satellite Server.

NOTE: This unit also assume the 'hammer' command is configured correctly and functions without prompting for username and password.  If it does not, you may need to make some changes to the config file: _/root/.hammer/cli.modules.d/foreman.yml_

The work in this unit will be performed partially on node1's command-line and then in the Satellite's WebUI.

Begin by connecting to node1.

.[root@workstation ~]$ 
----
ssh node1
----

On the node1 server, for those not interested in typing there is a cheat-script available to execute all the tasks within this unit.  Please do take the time to review the commands and their parameters if you opt to invoke the script.

[NOTE]
====
_Unit Cheat Scripts_
----
cheat-register-host.sh
----
====


[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official provisioning guide.

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/managing_hosts/[Managing Hosts]

== Overview of Host Management

A host is defined as any Red Hat Enterprise Linux system that Red Hat Satellite manages, physical or virtual. Virtual hosts may be deployed on any platform supported by Red Hat Satellite (ex: KVM, VMware vSphere, OpenStack, Amazon EC2, Rackspace Cloud Services, Google Compute Engine)

Red Hat Satellite enables host management at scale, including:

   * monitoring, 
   * provisioning, 
   * remote execution, 
   * configuration management, 
   * software management, and 
   * subscription management. 
   
Hosts can be managed through the Red Hat Satellite web UI or through command line tools like 'hammer'.

Once a host is entitled with a subscription, we refer to it as a 'Content Host'.

== Registration

.[root@node1 ~]$ 
----
subscription-manager register --serverurl=satellite.example.com  --org="ExampleCom" --activationkey="MyKey-DEV"
----

== Inspect Enabled Repos

.[root@node1 ~]$ 
----
subscription-manager repos
----

== Install Satellite Client Agent

.[root@node1 ~]$ 
----
yum install katello-agent

systemctl start goferd
----

== Install Tracer Agent

NOTE: Tracer is a tech-preview feature introduced in Satellite 6.3 and continues to be tech-preview in Satellite 6.5

Tracer helps administrators identify applications that need to be restarted after a Red Hat Enterprise Linux system is patched.

.[root@node1 ~]$ 
----
yum install katello-host-tools-tracer
----

== Upload System Info

To get our environment started ASAP, let's upload information about the host manually.

.[root@node1 ~]$ 
----
katello-package-upload

katello-tracer-upload
----

== Audit

At this point, switch to using the Satellite WebUI.

Go to 'Hosts -> All Hosts'
Select 'node1'

Expore the tabs for Facts, Content and Errata.

== Remediation

Once you are in the Errata tab for 'node1', select all errata and apply.

Host has now been patched.

== Additional Resources

Red Hat BLOG about Tracer

    * link:https://www.redhat.com/en/blog/introduction-tracer-feature-satellite[Introduction to the Tracer Feature]

[discrete]
== End of Unit

link:../SAT6-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
