:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Host Collections

.[root@workstation ~]$ 
----
whoami
----

[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official docs.

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.5/html/managing_hosts/chap-red_hat_satellite-managing_hosts-configuring_host_collections[Configuring Host Collections]

== Host Collections Overview

A host collection is a group of multiple content hosts (clients or systems). This feature enables the execution of actions on multiple hosts at once. 

== Create Host Collection

Select `Hosts->Host Collections`

Select `Create Host Collection`

Give the collection a name: "MyHostCollection"

Leave "Unlimited Hosts" selected (checked)

Give the collection a description: "Hosts that belong me"

Select `Save`

== Add Hosts

Within the Host Collection pane, select `Hosts`

Select `Add`

Select (check) our client nodes: `node1` `node2` `node3`

Select `Add Selected`

Within the Host Collections `Hosts` pane, select `List/Remove` and confirm clients were added

== Perform Actions

Within the Host Collections `Hosts` pane, select `List/Remove`

Select all hosts for this activity.

Within the Host Collections pane, select `Details`

On the right side of the pane `Details` pane, locate the list of *Actions*.  Careful, it's NOT the `Select Action` button in the top right, rather it is a list actions with links to specific activities.

Select `Package Installation, Removal, and Update`

You could just bring all your clients in the collection up to date (based on what is in the content view) by clicking `Update All Packages`, however in the interest of time we are only going to install a single package.

Check `Package` and enter "sos" in the text field.

Now select `Install`

Answer `Yes` to "Are you sure you want to install sos on the system(s) selected?"

Select `Done`

Select `Monitor->Tasks` to view progress and status

[discrete]
== End of Unit

link:../SAT6-Workshop.adoc#toc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
