:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Fundamental Host Management : Host Collections and Remote Jobs

[NOTE]
====
_Unit Cheat Scripts_
----
TBD
----
====


[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official provisioning guide.

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/managing_hosts/chap-managing_hosts-running_remote_jobs_on_hosts[Running Jobs on Hosts]

== Create a Job Template (Script)

== Create a Job Template (Ansible)

Hosts->Templates->Job Templates

Select 'New Job Template'

=== TAB: Template

Name: 'My Playbook - Sample Config'
Default: checked

[Template]
----
---
- hosts: all
  tasks:
  
  - name: copy resolv.conf file to tmp
    copy:
      remote_src: yes
      src: /etc/resolv.conf
      dest: /tmp/resolv.conf-back
      
  - name: install sample.conf
    copy:
      dest: /etc/sample.conf
      content: |
        # A sample configuration file created by an Ansible Job Template
        Hostname: {{ ansible_facts['nodename'] }}
        OS Family: {{ ansible_facts['os_family'] }}
        Release: {{ ansible_facts['lsb']['release'] }}
      backup: yes
----

=== TAB: Job

Job Category: 'My Playbooks'

Description Format: '%{job_category}: %{template_name}'

Provider Type: Ansible

=== TAB: Locations

Select and add your locations.

Now select 'Submit'

== Create a Host Collection

=== Create first Host Collection

Hosts->Hosts->Host Collections

Select Create Host Collection

Name: ExampleCom_Collection_1

Select 'Save'

=== Create second Host Collection

Hosts->Hosts->Host Collections

Select Create Host Collection

Name: ExampleCom_Collection_2

Select 'Save'

=== Add hosts to each collection

Register node2 and node3 to Satellite

Add node1 to Host_Collection_1

Add node1, node2 and node3 to Host_Collection_2

== Select Host Collection

Hosts->All Hosts

Filter: "host_collection = Host_Collection_1"

Select all hosts in collection

== Schedule Remote Job

With hosts properly selected

'Select Action' -> 'Schedule Remote Job'

Job Category: 'My Playbooks'
Job Template: 'My Playbook - Sample Config'

Select 'Submit'

Go inspect your clients.

== Alternative Ansible Job Template

If you are having problems getting the Sample Config template to work, try this simpler example.

Hosts->Templates->Job Templates

Select 'New Job Template'

=== TAB: Template

Name: 'My Playbook - Ping'
Default: checked

----
# Sample to test Ansible Playbook Execution
---
- hosts: all

  tasks:
  
  - name: Ping host
    ping:
----

=== TAB: Job

Job Category: 'My Playbooks'

Description Format: '%{job_category}: %{template_name}'

Provider Type: Ansible

=== TAB: Locations

Add your locations.

Select 'Submit' and try to schedule this job for your host-collection.

[discrete]
== End of Unit

*Next:* link:Host-Groups.adoc[Host Groups]

link:../SAT6-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
