:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Satellite & Red Hat Insights

[NOTE]
====
_Unit Cheat Scripts_
----
cheat-register-host.sh
----
====


[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official provisioning guide.

    * link:https://access.redhat.com/blogs/2184921/posts/3706641[configure Satellite 6.4 to execute Insights' remediation playbooks]

== Register with Satellite

Disable the default local repos.

.[root@node2 ~]$ 
----
sed -i 's/enabled=1/enabled=0/g' /etc/yum.repos.d/rhel7.repo
----

Register the client with the Satellite system.

.[root@node2 ~]$ 
----
subscription-manager register --serverurl=satellite.example.com  --org="ExampleCom" --activationkey="desktop-dev"
----

== Install the Insights Client Package

.[root@node2 ~]$ 
----
yum install -y insights-client
----

== Register the Client

.[root@node2 ~]$ 
----
redhat-access-insights --register
----

== View the Insights Report

Using the WebUI, simply go to the 'Insights -> Overview' report and you can poke around at the results.

[discrete]
== End of Unit

*Next:* link:Host-Groups.adoc[Host Groups]

link:../SAT6-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
