:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Host Provisioning

[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Many of the same steps we use here can be found in the official provisioning guide.

    * link:https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/provisioning_guide/initialization_script_for_provisioning_examples[Provisioning Guide - Appendix A]

== Provisioning Overview

== Add Kickstart Repos to Content View

Content -> Content Views

Select Desktop-R7

Yum Content -> Repositories

Add

Select `Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.5`

Add Repositories

(Top Right) `Publish New Version`

Promote

Select Desktop-DEV

== Create Provioning Template

Hosts -> Provisioning Templates

Filter: redhat

Clone 'Kickstart Default'

Change name to: 'Custom Desktop Kickstart'
Scroll to bottom, select 'Submit'

Filter: custom
Select 'Custom Desktop Kickstart'
Unselect 'Default'

Right before <% if salt_enabled %> add this block
----
<% if host_param('custom_dekstop_pkgs') == 'true' %>
@GNOME
@Graphical Administration Tools
@Guest Desktop Agents
@Remote Desktop Clients
@Virtualization Client
@Virtualization Tools
@Fonts
@X11
<% end -%>
----

=== Association

Move appropriate Operating Systems to `Selected Items` list

=== Locations

add your location to `Selected Items`

=== Organization

verify your organization is in the `Selected Items` list

Submit

####################

== Create Partition Table

Hosts -> Partition Tables

Create Partition Table
Name: `Custom Desktop Partitions`
Family: `Red Hat`

Template:
----
<%#
kind: ptable
name: Custom Desktop Partitions
model: Ptable
oses:
- CentOS
- Fedora
- RedHat
%>
zerombr
clearpart --all --initlabel

clearpart --drives=sda --all
part /boot --fstype=ext2 --size=512 --ondisk=sda --asprimary
part pv.01 --size=1024 --grow --ondisk=sda --asprimary
volgroup vg_rhel pv.01
logvol /     --fstype=ext4  --vgname=vg_rhel --name=root   --size=6144 --grow
logvol /var  --fstype=ext4  --vgname=vg_rhel --name=var    --size=4096
logvol /home --fstype=ext4 --vgname=vg_rhel --name=home   --size=2048
logvol /tmp  --fstype=ext4  --vgname=vg_rhel --name=tmp    --size=2048
logvol swap  --fstype=swap --vgname=vg_rhel --name=swap01 --size=2048
----

=== Locations

add your location to `Selected Items`

=== Organization

verify your organization is in the `Selected Items` list

Submit


####################

Enable Custom Kickstart in Operating System

Hosts -> Operating Systems

Select `Red Hat 7.5`

=== Partition Table

Add 'Custom Desktop Partitions` to Selected items

=== Templates

Provisioning tempate : Select Custom Desktop Kickstart






####################


== Create a Host Group

Configure -> Host Groups

Create

Name: Custom Desktop
Lifecycle Environment: Desktop-DEV
Content View: Desktop-R7
Content Source: satellite.example.com

=== Network

=== Operating System

Architecture: x86_64
Operating System: RedHat 7.5
Media Selection: Synced Content
Synced Content: Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.5
Partition Table: Custom Desktop Partitions
PXE loader: PXELinux BIOS
Root Pass: ********

=== Locations

Add location to `Selected items`



== Configure Discovery Rules

== Create Discovery Image

== Boot Client

[discrete]
== End of Unit

*Next:* link:Intro-Puppet.adoc[Introduction to Puppet]

link:../SAT6-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
