:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= PXE-Less Discovery

[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Red Hat's official documentation can be found publicly with the links provided below.  It is important to note that this workshop guide supports a very narrowly scoped and simple installation of the Openshift Container Platform (OCP).  Please refer to the official Red Hat documentation for complete information on the installation procedures.


    * PUT LINK TO PXE-LESS DISCVOERY REFERENCES HERE

Steps required for PXE-Less Discovery

  * Already Done
    * Install 'foreman-discovery-image' and 'rubygem-smart_proxy_discovery' packages on Satellite Server
    * Enable Red Hat Repos (including 'kickstart' repos)
    * Sync Red Hat Repos
    * Create Lifecycle
    * Create Content View (which includes 'kickstart' repos)
    * Publish Content View to Library
    * Promote Content View to LifeCycle
    
  * To Do
    * Create Custom Provisioning Template
    * Create Custom Partition Template
    * Modify the Operating System
    * Create a Domain
    * Create a Subnet
    * Create Activation Key
    * Create Host Group
    * Create Discovery Rules
    * Create Discovery Image
    * Mount Discovery Image to Client

== Create Provisioning Template

Hosts->Templates->Provisioning Templates

Search on 'kickstart default'

To the right of the template called "Kickstart default", select 'clone'

=== Adjust Provisioning Template Settings

==== TAB: Template

Change the name to "Kickstart custom"

==== TAB: Associations

Add 'Red Hat 7.5' to the 'Selected Items' list

==== TAB: Locations

Add our locations to the 'Selected items' list

Select 'Submit'

Do not make any further changes at this time.



== Create Partition Table

Hosts->Templates->Partition Table

Search on 'kickstart default'

To the right of the partition table called "Kickstart default", select 'clone'

=== Tab: Template

Change the name to "Kickstart Custom" and select 'Submit'

=== Tab: Locations

Add our locations to the 'Selected items' list

Select 'Submit'

Do not make any further changes at this time.



== Update Operating System

Hosts->Provisioning Setup->Operating Systems

Select 'Red Hat 7.5'

=== Tab: Partition Table

Select "Kickstart Custom" and all to 'Selected Items' list

Select 'Submit'

=== Tab: Templates

Provisioning Template: 'Kickstart Custom'
Discovery Kexec template: 'Discovery Red Hat kexec'



== Create a Domain

Satellite considers a domain and a DNS zone as the same thing.  That is, if you are planning to manage a site where all the machines are of the form hostname.somewhere.com then the domain is somewhere.com.

This allows Satellite to associate a puppet variable with a domain/site and automatically append this variable to all external node requests made by machines at that site.

The default domain is assumed to be 'example.com' and since we are only operating in the damain 'example.com' we have nothing further to do here.



== Create a Subnet

Yes it's required



== Create Activation Key

Content->LifeCycles->Activation Keys

Select 'Create Activation Key'

Name the key 'Custom Key'

Select the appropriate Environment

Select the appropriate Content View

Select 'Save'

Now that the Activation Key has been created, we need to make further associations.

=== Tab: Subscriptions

Select 'Add'

Choose the current entitlement to associate with this Activation Key.

Select 'Add Selected'

Return to the List/Remove tab and you should see the entitlement listed

That's it for now, we will leave everything else at it's default.



== Create Host Group

Configure->Host Groups

Select 'Create Host Group'

=== TAB: Host Group

Name: Custom
Lifecycle Environment: Dev
Content View: R7
Content Source: satellite.example.com

Leave everything else as default

=== TAB: Operating System

Architecture: x86_64
Operating System: RedHat 7.5
Media Selection: Synced Content
Synced Content: Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.5
Partition Table: 





== Create Discovery Rules
== Create Discovery Image
== Mount Discovery Image to Client





.[root@workstation OCP-Workshop]# - RAW INSTRUCTIONS
----

Configure the Discovery Red Hat Kexec

Switch to "Any Organization"
Hosts->Provisioning Templates
Select "Discovery Red Hat kexec"
Verify Associations
Add our custom Location
Add our custom Org


Create Custom Partition Table
Hosts->Templates/Partition Tables
Clone "Kickstart default"
Make adjustments:
Name: Oath-Workstation-PT
OS Family: Red Hat


EXAMPLE:

<%#
kind: ptable
name: My Workstation Partitions
model: Ptable
oses:
- CentOS
- Fedora
- RedHat
%>
zerombr
clearpart --all --initlabel

clearpart --drives=sda --all
part /boot --fstype=xfs --size=512 --ondisk=sda --asprimary
part pv.01 --size=1024 --grow --ondisk=sda --asprimary
volgroup vg_rhel pv.01
logvol /     --fstype=xfs  --vgname=vg_rhel --name=root   --size=6144 --grow
logvol /var  --fstype=xfs  --vgname=vg_rhel --name=var    --size=4096
logvol /home --fstype=xfs  --vgname=vg_rhel --name=home   --size=2048
logvol /tmp  --fstype=xfs  --vgname=vg_rhel --name=tmp    --size=2048
logvol swap  --fstype=swap --vgname=vg_rhel --name=swap01 --size=2048


## Associate with Organization

## Associate with with Operating System 

Hosts->Operating Systems
Partition Table Tab, add new custom partitioning scheme to  association table

Create Domain



Create Subnet



Create Activation Key

## Create Activation Key
Oath-Workstation-AK
Select Environment
Select Content View

## Add subscription

## Add Repository Sets


Hostgroup

## Create Host Group
Configure->Host Groups

## Network
Select Domain
I did not have to select Subnets

## Select Custom Partitioning Template
Operating System tab, select new partition scheme

## Parameters

## Global Parameter: don't upgrade packages during installation
package_upgrade=false

## Associate Activation Key



Create Ansible Role

cd /etc/ansible/roles
ansible-galaxy init Oath-Workstation-20181204

## ../tasks/main.yml

---
- name: INCLUDE| additional-pkgs.yml
  include_tasks: additional-pkgs.yml

---
- name: INCLUDE| enable-gui.yml
  include_tasks: enable-gui.yml


## ../tasks/additional-pkgs.yml

---
- name: YUM| Install misc required packages for desktop
  yum: name=screen,wget,git,net-tools,bind-utils,yum-utils,bash-completion,sos,psacct,lynx state=installed

## ../tasks/enable-gui.yml

---
- name: SHELL| Call systemctl to set graphical mode
  shell:
    cmd: systemctl set-default graphical.target


## Import Ansible Role
Configure->Ansible->Roles

## Add Ansible Role to Host Group


## Create Subnet


## Create Domains

Discovery Rule

Configure->Discovery Ruless

## Add Search
facts.oath-workstation=true

## Host Group
Select whatever we created above

## Enable Auto Discovery Provisioning
Administer->Settings / Discovered / "Auto provisioning"

POST Install Setup
## Continued Installation/Customization
?? updates

PROVISIONING BARE METAL HOSTS
Reference Documentation
https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/provisioning_guide/provisioning_bare_metal_hosts

## Associate Kexec provisioning template with our org/location
Select Organization to Any Organization
Select Location to Any Location
Hosts->Templates/Provisioning
Search kexec
Location & Org Tab, add our org and location
Save

## Create Puppet Environment and Associate it org/loc

## Create Host Group and Associate it org/loc

## Create Subnet and Associate it org/loc

## Copy ISO image to CD or USB thumb 
cd /usr/share/foreman-discovery-image





At the Client Procedures

INSTALLATION

## Boot Host/VM with Discovery ISO (non-auto / customized)
select DHCP / Manual
select provisioning interface
enter any facts (key=value pairs)
submit and be-discovered


## Back at the WebUI (If NOT Auto Provisioned)
Hosts->Discovered Host
  select provision
  if all options at correct stored in the Host Group it should kexec and launch

## Upgrade Host








EXTRA JUNK

## Remaster Discovery ISO

## Create custom discovery image (only if customizing the iso)
cd /usr/share/foreman-discovery-image

#
discovery-remaster foreman-discovery-image-3.5.3-1.iso "proxy.url=https://sat64-test.lab.linuxsoup.com proxy.type=server fdi.pxfactname1=oath fdi.pxfactvalue1=true fdi.pxauto=1"


##
goferd was pointing to wrong port (ie: old package from Common is NOT was to use)


## Hostname examples for Discovery Rules


<%= @host.facts['nmprimary_dhcp4_option_host_name'] %>

## GRUB2 config for discovery iso
cp foreman-discovery-iso-W.X.Y-Z.iso /boot

vi /etc/grub.d/40_custom

#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Discovery Image ISO" {
        set isofile="/foreman-discovery-image-3.5.3-1.iso"
        loopback loop (hd0,1)${isofile}
        syslinux_source (loop)/isolinux/isolinux.bin
        syslinux_configfile (loop)/isolinux/isolinux.cfg
}

## Provisioning Template Customization Example for %packages block
## set a parameter in the HostGroup "oath_workstation_pkgs = true"

<% if host_param('oath_workstation_pkgs') == 'true' %>
@GNOME
@Graphical Administration Tools
@Guest Desktop Agents
@Remote Desktop Clients
@Virtualization Client
@Virtualization Tools
@Fonts
@X11
<% end -%>

## Provisioning Template Customization Example for %post-install, right before ansible callback
## set a parameter in the HostGroup "oath_workstation_pkgs = true"

<% if host_param('oath_workstation_pkgs') == 'true' -%>
systemctl set-default graphical.target
<% end -%>




##Building Satellite Discovery Image
https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/provisioning_guide/provisioning_bare_metal_hosts#building_a_satellite_discovery_image


## Start & Stop Satellite Services
katello-service start
katello-service stop


## If you monkey with filesystems and volumes (ie: move things around)
restorecon -R {directory}


## Task cleanup
https://access.redhat.com/solutions/275573

----

[discrete]
== End of Unit

*Next:* link:Intro-Ansible.adoc[Introduction to Ansible]

link:../SAT6-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
