:sectnums:
:sectnumlevels: 2
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= PXE-Less Discovery

[discrete]
== Additional Reference Materials

NOTE: You are not required to reference outside documentation for these exercises.  This is informational only.

Red Hat's official documentation can be found publicly with the links provided below.  It is important to note that this workshop guide supports a very narrowly scoped and simple installation of the Openshift Container Platform (OCP).  Please refer to the official Red Hat documentation for complete information on the installation procedures.


    * PUT LINK TO PXE-LESS DISCVOERY REFERENCES HERE

Steps required for PXE-Less Discovery

  * Already Done
    * Install 'foreman-discovery-image' and 'rubygem-smart_proxy_discovery' packages on Satellite Server
    * Enable Red Hat Repos (including 'kickstart' repos)
    * Sync Red Hat Repos
    * Create Lifecycle
    * Create Content View (which includes 'kickstart' repos)
    * Publish Content View to Library
    * Promote Content View to LifeCycle
    
  * To Do
    * Enable 'Discovery Red Hat Kexec'
    * Create Custom Provisioning Template
    * Create Custom Partition Template
    * Modify the Operating System
    * Create a Domain
    * Create a Subnet
    * Create Activation Key
    * Create Host Group
    * Create Discovery Rules
    * Create Discovery Image
    * Mount Discovery Image to Client

== Enable Auto Discovery Provisioning

Administer->Settings

==== TAB: Discovered 

"Auto provisioning" : Yes



== Enable 'Discovery Red Hat Kexec'

Switch to "Any Organization"

Hosts->Provisioning Templates

Select "Discovery Red Hat kexec"

Verify Associations

Add our custom Location

Add our custom Org

== Create Custom Provisioning Template

Hosts->Templates->Provisioning Templates

Search on 'kickstart default'

To the right of the template called "Kickstart default", select 'clone'

=== Adjust Provisioning Template Settings

==== TAB: Template

Change the name to "Kickstart custom"

==== TAB: Associations

Add 'Red Hat 7.5' to the 'Selected Items' list

==== TAB: Locations

Add our locations to the 'Selected items' list

Select 'Submit'

Do not make any further changes at this time.



== Create Custom Partition Table

Hosts->Templates->Partition Table

Search on 'kickstart default'

To the right of the partition table called "Kickstart default", select 'clone'

=== Adjust Partition Template Settings

==== TAB: Template

Change the name to "Kickstart Custom" and select 'Submit'

==== TAB: Locations

Add our locations to the 'Selected items' list

Select 'Submit'

Do not make any further changes at this time.



== Update Operating System

Hosts->Provisioning Setup->Operating Systems

Select 'Red Hat 7.5'

=== Adjust Operating System Settings

==== TAB: Partition Table

Select "Kickstart Custom" and add to 'Selected Items' list

=== TAB: Templates

Provisioning Template: 'Kickstart Custom'
Discovery Kexec template: 'Discovery Red Hat kexec'

Select 'Submit'

Do not make any further changes at this time.



== Create a Domain

https://access.redhat.com/solutions/1165743

Click on Administer -> Organizations 
Click on "Domains" default domain should be listed, select it.
Click on Submit.
Click on Administer -> Locations 
Click on "Domains" default domain should be listed, select it.
Click on Submit.



== Create a Subnet

Enter the basic network info required for the client to communicate with the Satellite



== Create Activation Key

Content->LifeCycles->Activation Keys

Select 'Create Activation Key'

Name the key 'Custom Key'

Select the appropriate Environment

Select the appropriate Content View

Select 'Save'

Now that the Activation Key has been created, we need to make further associations.

=== Adjust Activation Key Settings

==== TAB: Subscriptions

Select 'Add'

Choose the current entitlement to associate with this Activation Key.

Select 'Add Selected'

Return to the List/Remove tab and you should see the entitlement listed

Select 'Submit'

Do not make any further changes at this time.



== Create Host Group

Configure->Host Groups

Select 'Create Host Group'

=== Adjust Host Group Settings

==== TAB: Host Group

Name: Custom
Lifecycle Environment: Dev
Content View: R7
Content Source: satellite.example.com

Leave everything else as default

==== TAB: Operating System

Architecture: x86_64
Operating System: RedHat 7.5
Media Selection: Synced Content
Synced Content: Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.5
Partition Table: 'Kickstart Custom'
PXE loader: PXELinux BIOS
Root Pass: redhat123

==== TAB: Locations

Add our location

==== TAB: Organization

Add our organization

Select 'Submit'

Do not make any further changes at this time.



== Create Discovery Rules

Configure->Discovery Rules

==== TAB: Primary

Name: Custom
Search: facts.custom=true
Host Group: Custom
Hostname: <%= @host.facts['nmprimary_dhcp4_option_host_name'] %>

==== TAB: Locations

add our location

==== Organization

Add our organization

Select 'Submit'

Do not make any further changes at this time.



## Enable Auto Discovery Provisioning
Administer->Settings / Discovered / "Auto provisioning"



== Create Discovery Image

We are going to create a discovery image inorder to inject some custom host facts.

cd /usr/share/foreman-discovery-image

discovery-remaster foreman-discovery-image-3.5.3-1.iso "proxy.url=https://satellite.lab.linuxsoup.com proxy.type=server fdi.pxfactname1=custom fdi.pxfactvalue1=true fdi.pxauto=1"

Take notice of the ISO that was created.  In the real world, you could now burn that image to a CDROM, USB stick or copy the image to your virtualization environment to mount to your VM.

Luckily that work has already been done for you.



== Mount Discovery Image to Client



== Customize the Partition Template

----
<%#
kind: ptable
name: My Workstation Partitions
model: Ptable
oses:
- CentOS
- Fedora
- RedHat
%>
zerombr
clearpart --all --initlabel

clearpart --drives=sda --all
part /boot --fstype=ext2 --size=512 --ondisk=sda --asprimary
part pv.01 --size=16000 --grow --ondisk=sda --asprimary
volgroup vg_rhel pv.01
logvol /     --fstype=ext4 --vgname=vg_rhel --name=root   --size=6000 --grow
logvol /var  --fstype=ext4 --vgname=vg_rhel --name=var    --size=4000
logvol /home --fstype=ext4 --vgname=vg_rhel --name=home   --size=2000
logvol /tmp  --fstype=ext4 --vgname=vg_rhel --name=tmp    --size=2000
logvol swap  --fstype=swap --vgname=vg_rhel --name=swap01 --size=2000
----


== Customize the Provisioning Template

Insert this block in %packages block 


----
<% if host_param('custom') == 'true' %>
@GNOME
@Graphical Administration Tools
@Guest Desktop Agents
@Remote Desktop Clients
@Virtualization Client
@Virtualization Tools
@Fonts
@X11
<% end -%>
----


Insert thisblock in %post-install, right before ansible callback

----
<% if host_param('custom') == 'true' -%>
systemctl set-default graphical.target
<% end -%>
----




.[root@workstation OCP-Workshop]# - REMAINING RAW INSTRUCTIONS
----

## Parameters

Create Ansible Role

cd /etc/ansible/roles
ansible-galaxy init Oath-Workstation-20181204

## ../tasks/main.yml

---
- name: INCLUDE| additional-pkgs.yml
  include_tasks: additional-pkgs.yml

---
- name: INCLUDE| enable-gui.yml
  include_tasks: enable-gui.yml


## ../tasks/additional-pkgs.yml

---
- name: YUM| Install misc required packages for desktop
  yum: name=screen,wget,git,net-tools,bind-utils,yum-utils,bash-completion,sos,psacct,lynx state=installed

## ../tasks/enable-gui.yml

---
- name: SHELL| Call systemctl to set graphical mode
  shell:
    cmd: systemctl set-default graphical.target


## Import Ansible Role
Configure->Ansible->Roles

## Add Ansible Role to Host Group


## Create Puppet Environment and Associate it org/loc

## Create Host Group and Associate it org/loc

## Create Subnet and Associate it org/loc

## Copy ISO image to CD or USB thumb 
cd /usr/share/foreman-discovery-image





At the Client Procedures

INSTALLATION

## Boot Host/VM with Discovery ISO (non-auto / customized)
select DHCP / Manual
select provisioning interface
enter any facts (key=value pairs)
submit and be-discovered


## Back at the WebUI (If NOT Auto Provisioned)
Hosts->Discovered Host
  select provision
  if all options at correct stored in the Host Group it should kexec and launch

## Upgrade Host








EXTRA JUNK

## Remaster Discovery ISO

## Create custom discovery image (only if customizing the iso)
cd /usr/share/foreman-discovery-image

#
discovery-remaster foreman-discovery-image-3.5.3-1.iso "proxy.url=https://sat64-test.lab.linuxsoup.com proxy.type=server fdi.pxfactname1=oath fdi.pxfactvalue1=true fdi.pxauto=1"


##
goferd was pointing to wrong port (ie: old package from Common is NOT was to use)


## Hostname examples for Discovery Rules


<%= @host.facts['nmprimary_dhcp4_option_host_name'] %>

## GRUB2 config for discovery iso
cp foreman-discovery-iso-W.X.Y-Z.iso /boot

vi /etc/grub.d/40_custom

#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Discovery Image ISO" {
        set isofile="/foreman-discovery-image-3.5.3-1.iso"
        loopback loop (hd0,1)${isofile}
        syslinux_source (loop)/isolinux/isolinux.bin
        syslinux_configfile (loop)/isolinux/isolinux.cfg
}

## Provisioning Template Customization Example for %packages block
## set a parameter in the HostGroup "oath_workstation_pkgs = true"

<% if host_param('oath_workstation_pkgs') == 'true' %>
@GNOME
@Graphical Administration Tools
@Guest Desktop Agents
@Remote Desktop Clients
@Virtualization Client
@Virtualization Tools
@Fonts
@X11
<% end -%>

## Provisioning Template Customization Example for %post-install, right before ansible callback
## set a parameter in the HostGroup "oath_workstation_pkgs = true"

<% if host_param('oath_workstation_pkgs') == 'true' -%>
systemctl set-default graphical.target
<% end -%>




##Building Satellite Discovery Image
https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/provisioning_guide/provisioning_bare_metal_hosts#building_a_satellite_discovery_image


## Start & Stop Satellite Services
katello-service start
katello-service stop


## If you monkey with filesystems and volumes (ie: move things around)
restorecon -R {directory}


## Task cleanup
https://access.redhat.com/solutions/275573

----

[discrete]
== End of Unit

*Next:* link:Intro-Ansible.adoc[Introduction to Ansible]

link:../SAT6-Workshop.adoc[Return to TOC]

////
Always end files with a blank line to avoid include problems.
////
