##
##    First, need to set up the deployhost with
##    needed software, services and settings
##



- hosts: myDeployhost
  tasks:

    - debug: msg="**** BEGIN SETUP  ****"

    - include_role:
        name: xtoph_deploy
      vars:
        xtoph_deploy_action: "setup"
      when: xtoph_deploy_cmd == "setup" or
            xtoph_deploy_cmd == "setup+"

    - debug: msg="**** END SETUP  ****"



##
##    Next, execute undeploy activities
##
##     NOTE: hosts may (or may not) exist, 
##           majority of tasks run as 'delegate_to'
##           and so we don't gather_facts
##



- hosts: myBastion,mySatellite,myNodes,!myShelter
  gather_facts: no
  serial: 3
  tasks:

    - debug: msg="**** BEGIN UNDEPLOY  ****"

    - include_role:
        name: xtoph_deploy
      vars:
        xtoph_deploy_action: "undeploy"
      when: xtoph_deploy_cmd == "undeploy" or
            xtoph_deploy_cmd == "redeploy"

    - debug: msg="**** END UNDEPLOY  ****"



##
##     Before we start deploying systems, we
##     need to ensure certain basics are configured.
##     Run the 'deploy_preprocess' to:
##       - generate MAC addresses if needed
##       - add DNS entries to /etc/hosts
##       - maybe more stuff, go look!
##



- hosts: myBastion,mySatellite,myNodes,!myShelter
  gather_facts: no
  serial: 3
  tasks:

    - debug: msg="**** BEGIN PREPROCESS  ****"

    - include_role:
        name: xtoph_deploy
      vars:
        xtoph_deploy_action: "preprocess"
      when: xtoph_deploy_cmd == "deploy" or
            xtoph_deploy_cmd == "setup+" or
            xtoph_deploy_cmd == "redeploy"

    - debug: msg="**** END PREPROCESS  ****"



##
##     For the SAT 6 Workshop, there are 
##     no concurrency issues, so proceed 
##     to deploy everything at once
##
##     NOTE: for same reasons listed above
##           don't gather_facts 
##
##     NOTE: 'serial: #' limits concurrent 
##           deployments and resolves problems
##           related to disk space and i/o
##           limits
##



- hosts: myBastion,mySatellite,myNodes,!myShelter
  gather_facts: no
  serial: 3
  tasks:

    - debug: msg="**** BEGIN DEPLOY  ****"

    - include_role:
        name: xtoph_deploy
      vars:
        xtoph_deploy_action: "deploy"
      when: xtoph_deploy_cmd == "deploy" or
            xtoph_deploy_cmd == "setup+" or
            xtoph_deploy_cmd == "redeploy"

    - debug: msg="**** END DEPLOY  ****"



##
##    All nodes should be deployed
##    So proceed to configure the workshop 
## 

- import_playbook: playbooks/deployer-preinstall-satellite.yml
  when: xtoph_deploy_cmd == "deploy" or
        xtoph_deploy_cmd == "setup+" or
        xtoph_deploy_cmd == "redeploy"

- import_playbook: playbooks/sat6.yml
  when: xtoph_deploy_cmd == "deploy" or 
        xtoph_deploy_cmd == "redeploy" or 
        xtoph_deploy_cmd == "setup+" or
        xtoph_deploy_cmd=="workshop"

- import_playbook: playbooks/deployer-postinstall-satellite.yml
  when: xtoph_deploy_cmd == "deploy" or
        xtoph_deploy_cmd == "setup+" or
        xtoph_deploy_cmd == "redeploy"

