sat6_assets:

  "6.3":
    name: "satellite"
    version: "6.3"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.3-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-satellite-6.3-puppet4-rpms"
    stop_cmd: "katello-service stop"
    start_cmd: "katello-service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ myOrganization }} --foreman-initial-location {{ myLocation }} --foreman-admin-username {{ myAdminName }} --foreman-admin-password {{ myAdminPW }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ myVG }}"
        path:   "/var/lib/pgsql"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.4":
    name: "satellite"
    version: "6.4"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.4-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.6-rpms"
    stop_cmd: "katello-service stop"
    start_cmd: "katello-service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ myOrganization }} --foreman-initial-location {{ myLocation }} --foreman-admin-username {{ myAdminName }} --foreman-admin-password {{ myAdminPW }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ myVG }}"
        path:   "/var/lib/pgsql"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.5":
    name: "satellite"
    version: "6.5"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.5-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.6-rpms"
    stop_cmd: "katello-service stop"
    start_cmd: "katello-service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ myOrganization }} --foreman-initial-location {{ myLocation }} --foreman-admin-username {{ myAdminName }} --foreman-admin-password {{ myAdminPW }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ myVG }}"
        path:   "/var/lib/pgsql"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.6":
    name: "satellite"
    version: "6.6"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.6-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.8-rpms"
    stop_cmd: "katello-service stop"
    start_cmd: "katello-service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization '{{ myOrganization }}' --foreman-initial-location '{{ myLocation }}' --foreman-initial-admin-username '{{ myAdminName }}' --foreman-initial-admin-password '{{ myAdminPW }}' --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ myVG }}"
        path:   "/var/lib/pgsql"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.7":
    name: "satellite"
    version: "6.7"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.7-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.8-rpms"
    stop_cmd: "katello-service stop"
    start_cmd: "katello-service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ myOrganization }} --foreman-initial-location {{ myLocation }} --foreman-initial-admin-username {{ myAdminName }} --foreman-initial-admin-password {{ myAdminPW }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ myVG }}"
        path:   "/var/lib/pgsql"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.8":
    name: "satellite"
    version: "6.8"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.8-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.9-rpms"
    stop_cmd: "katello-service stop"
    start_cmd: "katello-service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ myOrganization }} --foreman-initial-location {{ myLocation }} --foreman-initial-admin-username {{ myAdminName }} --foreman-initial-admin-password {{ myAdminPW }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ myVG }}"
        path:   "/var/lib/pgsql"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.9":
    name: "satellite"
    version: "6.9"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.9-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.9-rpms"
    stop_cmd: "satellite-maintain service stop"
    start_cmd: "satellite-maintain service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ myOrganization }} --foreman-initial-location {{ myLocation }} --foreman-initial-admin-username {{ myAdminName }} --foreman-initial-admin-password {{ myAdminPW }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ myVG }}"
        path:   "/var/opt/rh/rh-postgresql2"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ myVG }}"
        path:   "/var/cache"
        size:   "10"
