sat6_assets:

  "6.3":
    name: "satellite"
    version: "6.3"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.3-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-satellite-6.3-puppet4-rpms"
    product_repos: "Red Hat Enterprise Linux 7 Server (RPMs),Red Hat Satellite Tools {{ workshop_vars.satellite_version }} (for RHEL 7 Server) (RPMs)"
    stop_cmd: "katello-service stop"
    start_cmd: "katello-service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ workshop_vars.myOrganization }} --foreman-initial-location {{ workshop_vars.myLocation }} --foreman-admin-username {{ satellite_credentials.username }} --foreman-admin-password {{ satellite_credentials.password }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pgsql"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.4":
    name: "satellite"
    version: "6.4"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.4-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.6-rpms"
    product_repos: "Red Hat Enterprise Linux 7 Server (RPMs),Red Hat Satellite Tools {{ workshop_vars.satellite_version }} (for RHEL 7 Server) (RPMs)"
    stop_cmd: "katello-service stop"
    start_cmd: "katello-service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ workshop_vars.myOrganization }} --foreman-initial-location {{ workshop_vars.myLocation }} --foreman-admin-username {{ satellite_credentials.username }} --foreman-admin-password {{ satellite_credentials.password }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pgsql"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.5":
    name: "satellite"
    version: "6.5"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.5-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.6-rpms"
    product_repos: "Red Hat Enterprise Linux 7 Server (RPMs),Red Hat Satellite Tools {{ workshop_vars.satellite_version }} (for RHEL 7 Server) (RPMs)"
    stop_cmd: "katello-service stop"
    start_cmd: "katello-service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ workshop_vars.myOrganization }} --foreman-initial-location {{ workshop_vars.myLocation }} --foreman-admin-username {{ satellite_credentials.username }} --foreman-admin-password {{ satellite_credentials.password }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pgsql"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.6":
    name: "satellite"
    version: "6.6"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.6-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.8-rpms"
    product_repos: "Red Hat Enterprise Linux 7 Server (RPMs),Red Hat Satellite Tools {{ workshop_vars.satellite_version }} (for RHEL 7 Server) (RPMs)"
    stop_cmd: "katello-service stop"
    start_cmd: "katello-service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization '{{ workshop_vars.myOrganization }}' --foreman-initial-location '{{ workshop_vars.myLocation }}' --foreman-initial-admin-username '{{ satellite_credentials.username }}' --foreman-initial-admin-password '{{ satellite_credentials.password }}' --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pgsql"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.7":
    name: "satellite"
    version: "6.7"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.7-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.8-rpms"
    product_repos: "Red Hat Enterprise Linux 7 Server (RPMs),Red Hat Satellite Tools {{ workshop_vars.satellite_version }} (for RHEL 7 Server) (RPMs)"
    stop_cmd: "katello-service stop"
    start_cmd: "katello-service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ workshop_vars.myOrganization }} --foreman-initial-location {{ workshop_vars.myLocation }} --foreman-initial-admin-username {{ satellite_credentials.username }} --foreman-initial-admin-password {{ satellite_credentials.password }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pgsql"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.8":
    name: "satellite"
    version: "6.8"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.8-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.9-rpms"
    product_repos: "Red Hat Enterprise Linux 7 Server (RPMs),Red Hat Satellite Tools {{ workshop_vars.satellite_version }} (for RHEL 7 Server) (RPMs)"
    stop_cmd: "katello-service stop"
    start_cmd: "katello-service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ workshop_vars.myOrganization }} --foreman-initial-location {{ workshop_vars.myLocation }} --foreman-initial-admin-username {{ satellite_credentials.username }} --foreman-initial-admin-password {{ satellite_credentials.password }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pgsql"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.9":
    name: "satellite"
    version: "6.9"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.9-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.9-rpms"
    product_repos: "Red Hat Enterprise Linux 7 Server (RPMs),Red Hat Satellite Tools {{ workshop_vars.satellite_version }} (for RHEL 7 Server) (RPMs)"
    stop_cmd: "satellite-maintain service stop"
    start_cmd: "satellite-maintain service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ workshop_vars.myOrganization }} --foreman-initial-location {{ workshop_vars.myLocation }} --foreman-initial-admin-username {{ satellite_credentials.username }} --foreman-initial-admin-password {{ satellite_credentials.password }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/opt/rh/rh-postgresql2"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.10":
    name: "satellite"
    version: "6.10"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.10-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.9-rpms"
    product_repos: "Red Hat Enterprise Linux 7 Server (RPMs),Red Hat Satellite Tools {{ workshop_vars.satellite_version }} (for RHEL 7 Server) (RPMs)"
    stop_cmd: "satellite-maintain service stop"
    start_cmd: "satellite-maintain service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ workshop_vars.myOrganization }} --foreman-initial-location {{ workshop_vars.myLocation }} --foreman-initial-admin-username {{ satellite_credentials.username }} --foreman-initial-admin-password {{ satellite_credentials.password }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/opt/rh/rh-postgresql2"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.11":
    name: "satellite"
    version: "6.11"
    repos: "rhel-7-server-rpms,rhel-7-server-satellite-6.11-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.9-rpms"
    product_repos: "Red Hat Enterprise Linux 7 Server (RPMs),Red Hat Satellite Tools {{ workshop_vars.satellite_version }} (for RHEL 7 Server) (RPMs)"
    stop_cmd: "satellite-maintain service stop"
    start_cmd: "satellite-maintain service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ workshop_vars.myOrganization }} --foreman-initial-location {{ workshop_vars.myLocation }} --foreman-initial-admin-username {{ satellite_credentials.username }} --foreman-initial-admin-password {{ satellite_credentials.password }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      mongodb:
        lv:     "mongodb"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/mongodb"
        size:   "50"
      pulp:
        lv:     "pulp"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pulp"
        size:   "100"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/opt/rh/rh-postgresql2"
        size:   "10"
      squid:
        lv:     "squid"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/spool/squid"
        size:   "10"
      cache:
        lv:     "cache"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.12":
    name: "satellite"
    version: "6.12"
    repos: "rhel-8-for-x86_64-baseos-rpms,rhel-8-for-x86_64-appstream-rpms,satellite-6.12-for-rhel-8-x86_64-rpms,satellite-maintenance-6.12-for-rhel-8-x86_64-rpms"
    product_repos: "Red Hat Enterprise Linux 7 Server (RPMs),Red Hat Satellite Client 6 (for RHEL 7 Server) (RPMs)"
    product_sets: 
        "Red Hat Enterprise Linux 7 Server (RPMs)":
            label: "rhel-7-server-rpms"
            product: "Red Hat Enterprise Linux Server"
            basearch: "x86_64"
            releasever: "7Server"
            repo_name: "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"
        "Red Hat Satellite Client 6 (for RHEL 7 Server) (RPMs)":
            label: "rhel-7-server-satellite-client-6-rpms"
            product: "Red Hat Enterprise Linux Server"
            basearch: "x86_64"
            releasever: ""
            repo_name: "Red Hat Satellite Client 6 for RHEL 7 Server RPMs x86_64"
    stop_cmd: "satellite-maintain service stop"
    start_cmd: "satellite-maintain service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ workshop_vars.myOrganization }} --foreman-initial-location {{ workshop_vars.myLocation }} --foreman-initial-admin-username {{ satellite_credentials.username }} --foreman-initial-admin-password {{ satellite_credentials.password }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      puppet:
        lv:     "puppet"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/opt/puppetlabs"
        size:   "5"
      pulp:
        lv:     "pulp"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pulp"
        size:   "160"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pgsql"
        size:   "20"
      cache:
        lv:     "cache"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/cache"
        size:   "10"

  "6.13":
    name: "satellite"
    version: "6.12"
    repos: "rhel-8-for-x86_64-baseos-rpms,rhel-8-for-x86_64-appstream-rpms,satellite-6.13-for-rhel-8-x86_64-rpms,satellite-maintenance-6.13-for-rhel-8-x86_64-rpms"
    product_repos: "Red Hat Enterprise Linux 7 Server (RPMs),Red Hat Satellite Client 6 (for RHEL 7 Server) (RPMs)"
    product_sets:
        "Red Hat Enterprise Linux 7 Server (RPMs)":
            label: "rhel-7-server-rpms"
            product: "Red Hat Enterprise Linux Server"
            basearch: "x86_64"
            releasever: "7Server"
            repo_name: "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"
        "Red Hat Satellite Client 6 (for RHEL 7 Server) (RPMs)":
            label: "rhel-7-server-satellite-client-6-rpms"
            product: "Red Hat Enterprise Linux Server"
            basearch: "x86_64"
            releasever: ""
            repo_name: "Red Hat Satellite Client 6 for RHEL 7 Server RPMs x86_64"
    stop_cmd: "satellite-maintain service stop"
    start_cmd: "satellite-maintain service start"
    install_cmd: "satellite-installer --scenario satellite --foreman-initial-organization {{ workshop_vars.myOrganization }} --foreman-initial-location {{ workshop_vars.myLocation }} --foreman-initial-admin-username {{ satellite_credentials.username }} --foreman-initial-admin-password {{ satellite_credentials.password }} --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false"
    fs_data:
      puppet:
        lv:     "puppet"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/opt/puppetlabs"
        size:   "5"
      pulp:
        lv:     "pulp"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pulp"
        size:   "160"
      pgsql:
        lv:     "pgsql"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/lib/pgsql"
        size:   "20"
      cache:
        lv:     "cache"
        vg:     "{{ workshop_vars.myVG }}"
        path:   "/var/cache"
        size:   "10"





