##
## CUSTOM PLATFORM PROFILES
##

libvirt_nat:

    type:        "libvirt"
    host_fqdn:   "localhost"
    host_ip:     "localhost"
    description: "Custom platform libvirt_nat: private nat'd net, nested_virt"

    nested_virt_enable: true

    vm:
      name: "{{ xtoph_vars.clustername }}-{{ inventory_hostname }}"

    kickstart:
        description: "hints to where installers can find devices"
        netdev:  "{{ h_netDEV | default('eno1') }}"
        blkdev:  "{{ h_blkDEV | default('sda') }}"

    network:
        default:

            description:       "default libvirt network parameters"
            network_name:      "virbr_{{ xtoph_vars.clustername }}"
            fwd_type:          "nat"
            bridge_netdev:     ""
            undeploy:          true
            model:             "virtio"

            basedomain:        "{{ workshop_vars.network_basedomain }}"
            network:           "{{ workshop_vars.network_network    }}"
            netmask:           "{{ workshop_vars.network_netmask    }}"
            broadcast:         "{{ workshop_vars.network_broadcast  }}"
            prefix:            "{{ workshop_vars.network_prefix     }}"
            gateway:           "{{ workshop_vars.network_gateway    }}"
            nameserver:        "{{ workshop_vars.network_nameserver }}"
            timeserver:        "{{ workshop_vars.network_timeserver }}"
            fqdn:              "{{ workshop_extras.network_fqdn     }}"

    storage:
        default:

            description: "default libvirt storage parameters"
            qcow_dir: "/home/virt-images"
            bus: "virtio"
            sparse: "true"

