##
##    !! WARNING !!  Ansible only interprets 'True' and 'False'
##                   as booleans when reading ini files.  Other
##                   values such as 'true' or 'false' would be 
##                   interpreted as strings and would break various
##                   logic tests.  
##
##                   When reading YML files, booleans can take on
##                   many forms and be interpreted correctly.
##
##                   For consistency, only use unquoted booleans: True & False

all: 

  vars:

    ## ----------------------------------------
    ##    Workshop Variables

    workshop_vars:

      clustername:           "sat6ovirt"

      satellite_version:     "6.9"
      manifest_filename:     "manifest-v69.zip"

      artifacts_directory:   "/root/sat6-artifacts"
      
      ## Network Parms

      network_basedomain:    "example.com"
      network_network:       "192.168.1.0"
      network_netmask:       "255.255.255.0"
      network_broadcast:     "192.168.1.255"
      network_prefix:        "24"
      network_gateway:       "192.168.1.1"
      network_nameserver:    "192.168.1.30"
      network_timeserver:    "192.168.1.60"

      ## Satellite Parms

      myDisk:                "/dev/sdb"
      myVG:                  "sat_vg"
      
      myLocation:            "USA"
      myOrganization:        "ExampleCom"

#      myAdminName:           "{{ sat6_AdminName }}"
#      myAdminPW:             "{{ sat6_AdminPW   }}"
      
      myLifecycleName_1:     "MyLifecycle-DEV"
      myLifecycleName_2:     "MyLifecycle-QA"
      myLifecycleName_3:     "MyLifecycle-PROD"
      
      myContentViewName:     "MyContent RHEL 7"
      
      myActivationKeyName_1: "MyKey-DEV"
      myActivationKeyName_2: "MyKey-PROD"
      
      myJobTemplateCategory: "MyTemplates"
      myJobTemplateName_1:   "MyTemplate: Ping"
      myJobTemplateName_2:   "MyTemplate: Sample Config"
      
      myHostCollectionName:  "MyCollection"

      myHostGroupName:       "MyHostGroup"
      
      myDiscoveryRuleName:   "MyRule"
      myDiscoveryFact:       "MyFact"

      http_proxy:            ""
      https_proxy:           ""

      bastion:

        firewalld:           True
        dns:                 True
        dhcp:                False
        dhcp_pxe:            False
        dhcp_uefi_http:      False
        haproxy:             False
        matchbox:            False
        nfs:                 False
        ntp:                 False
        workshop_user:       True
        workshop_materials:  True
        desktop_gui:         True
        desktop_chrome:      True
        desktop_vnc:         True

    workshop_extras:

      network_fqdn:         "{{ workshop_vars.clustername }}.{{ workshop_vars.network_basedomain }}"



    ## ----------------------------------------
    ##    Xtoph Deploy Variables

    xtoph_vars:

      deployhost_ip:       "192.168.1.170" 
      clustername:         "{{ workshop_vars.clustername }}"






## ----------------------------------------
## HOSTGROUPS & VARS
## ----------------------------------------



myDeployhost:
  hosts:
    deployer:
      h_pubIP: "{{ xtoph_vars.deployhost_ip }}"
  vars:
    ansible_connection: local



## -----------------



myBastion:
  hosts:
    bastion:
      h_pubIP: "192.168.1.120"
  vars:
    ansible_host: "{{ inventory_hostname }}.{{ workshop_extras.network_fqdn }}"
    h_hwPROF:  "ovirt_sda"
    h_plPROF:  "sat6_ovirt_platform"
    h_rsPROF:  "bastion"
    h_ksPROF:  "rhel79-bootiso"
    h_netDEV:  "eth0"
    h_blkDEV:  "sda"



## -----------------



mySatellite:
  hosts:
    satellite:
      h_pubIP: "192.168.1.121"
  vars: 
    ansible_host: "{{ inventory_hostname }}.{{ workshop_extras.network_fqdn }}"
    h_hwPROF:  "ovirt_sda"
    h_plPROF:  "sat6_ovirt_platform"
    h_rsPROF:  "sat6"
    h_ksPROF:  "rhel79-bootiso"
    h_netDEV:  "eth0"
    h_blkDEV:  "sda"



## -----------------



myNodes:
  hosts:
    node1:
      h_pubIP: "192.168.1.122" 
    node2:
      h_pubIP: "192.168.1.123" 
    node3:
      h_pubIP: "192.168.1.124"

  vars: 
    ansible_host: "{{ inventory_hostname }}.{{ workshop_extras.network_fqdn }}"
    h_hwPROF:  "ovirt_sda"
    h_plPROF:  "sat6_ovirt_platform"
    h_rsPROF:  "tiny"
    h_blkDEV:  "sda"


    ## RHEL 7
    # h_ksPROF:  "rhel79-bootiso"
    # h_netDEV:  "eth0"

    ## CENTOS 7
    h_ksPROF:  "centos7-netinstall"
    h_netDEV:  "eth0"

    ## RHEL 8
    # h_ksPROF: "rhel84-bootiso"
    # h_netDEV: "ens3"
   

 
## -----------------



myShelter:
  hosts:
    satellite:

