## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##
##

---
- hosts: mySatellite

  tasks:

  - name: "deployer-postdeploy-tasks : create artifacts directory"
    file:
      path: "{{ workshop_vars.artifacts_directory }}"
      mode: "0700"
      state: directory

  - name: "deployer-postdeploy-tasks: deploy manifest"
    copy:
      src: "../config/{{ workshop_vars.manifest_filename }}"
      dest: "{{ workshop_vars.artifacts_directory }}"
      owner: root
      group: root
      mode: 0600

