- hosts: localhost

  tasks:



  - name: "deployer-predeploy-tasks : stat manifest"
    stat: path="../config/{{ workshop_vars.manifest_filename }}"
    register: test_manifest



  - name: "deployer-predeploy-tasks : fail if manifest absent"
    fail: msg="COPY YOUR SATELLITE MANIFEST HERE ./config/{{ workshop_vars.manifest_filename }}"
    when: test_manifest.stat.exists == false
