---
- hosts: mySatellite
  tasks:
  
    - name: "YUM install satellite packages"
      yum: name=satellite,sos,foreman-discovery-image state=installed

    - name: "CMD install satellite"
      shell: 
        cmd: |
          satellite-installer --scenario satellite \
          --foreman-initial-organization "{{ myOrganization }}" \
          --foreman-initial-location "{{ myLocation }}" \
          --foreman-initial-admin-username "{{ myAdminName }}" \
          --foreman-initial-admin-password "{{ myAdminPW }}" \
          --foreman-proxy-dns-managed=false \
          --foreman-proxy-dhcp-managed=false
          
