
## Authors: 
##   Christoph Doerbeck
##
## Summary:
##

---
- hosts: mySatellite
  tasks:



  - name: "sat6-preinstall-registration: collect RHSM username"
    block:

      - pause:
          prompt: "Enter RHSM username: "
          echo: yes
        register: prompt_username

      - set_fact:
          rhsm_username: "{{ prompt_username.user_input }}"

    when: rhsm_username is not defined or 
          rhsm_username == ""



  - name: "sat6-preinstall-registration: collect RHSM password"
    block:

      - pause:
          prompt: "Enter RHSM password: "
          echo: no
        register: prompt_password

      - set_fact:
          rhsm_password: "{{ prompt_password.user_input }}"

    when: rhsm_password is not defined or 
          rhsm_password == ""



  - name: "sat6-preinstall-registration: rhsm register"
    redhat_subscription:
      state: present
      pool: "Red Hat Satellite.*Subscription"
      force_register: yes
      username: "{{ rhsm_username }}"
      password: "{{ rhsm_password }}"
  
