
## Authors: 
##   Christoph Doerbeck
##
## Summary:
##

---
- hosts: mySatellite, !myShelter
  tasks:



  ##
  ##    Prompt for username/pass is rhsm_username
  ##    is not defined
  ##

  - block:

      - name: "SAT6-PREINSTALL-REGISTRATION: collect RHN username and password"
        pause:
          prompt: "Enter RHSM username: "
          echo: yes
        register: prompt_username
    
      - pause:
          prompt: "Enter RHN password: "
          echo: no
        register: prompt_password

      - set_fact:
          rhsm_username: prompt_username.user_input
          rhsm_password: prompt_password.user_input

    when: rhsm_username is undefined or rhsm_password is undefined

  ##
  ##    Register system
  ##

  - name: "SAT6-PREINSTALL-REGISTRATION: rhsm register"
    redhat_subscription:
      state: present
      pool: "Red Hat Satellite.*Subscription"
      force_register: yes
      username: "{{ rhsm_username }}"
      password: "{{ rhsm_password }}"
  
