
---
- hosts: nodes
  tasks:

    - name: "CMD remove older katello certs"
      shell:
        cmd: |
          yum remove -y katello-ca-consumer*.noarch

    - name: "YUM install satellite crt"
      yum: name=http://satellite.example.com/pub/katello-ca-consumer-satellite.example.com-1.0-1.noarch.rpm state=installed

    - name: "CMD clear yum cache"
      shell:                                                                                           
        cmd: |                                                                                         
          rm -rf /var/cache/yum/*

    - name: "TEMPLATE install cheat-(scripts) in /usr/local/bin"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'cheat-register-host.j2',           dest: '/usr/local/bin/cheat-register-host.sh'}

- hosts: satellite
  tasks:

    - name: "TEMPLATE install cheat-(scripts) in /usr/local/bin"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'cheat-repos-sync.j2',           dest: '/usr/local/bin/cheat-repos-sync.sh'}
        - {src: 'cheat-repos-enable.j2',         dest: '/usr/local/bin/cheat-repos-enable.sh'}
        - {src: 'cheat-repos-policy.j2',         dest: '/usr/local/bin/cheat-repos-policy.sh'}
        - {src: 'cheat-app-lifecycles.j2',       dest: '/usr/local/bin/cheat-app-lifecycles.sh'}
        - {src: 'cheat-cv-create.j2',            dest: '/usr/local/bin/cheat-cv-create.sh'}
        - {src: 'cheat-cv-publish.j2',           dest: '/usr/local/bin/cheat-cv-publish.sh'}
        - {src: 'cheat-cv-promote.j2',           dest: '/usr/local/bin/cheat-cv-promote.sh'}
        - {src: 'cheat-cv-add-extras.j2',        dest: '/usr/local/bin/cheat-cv-add-extras.sh'}
        - {src: 'cheat-ak-create.j2',            dest: '/usr/local/bin/cheat-ak-create.sh'}
        - {src: 'cheat-ak-attach-subs.j2',       dest: '/usr/local/bin/cheat-ak-attach-subs.sh'}
        - {src: 'cheat-ak-autoenable.j2',        dest: '/usr/local/bin/cheat-ak-autoenable.sh'}

    - name: "CMD yum clean all"
      shell:                                                                                           
        cmd: |                                                                                         
          yum clean all
