
## Authors: 
##   Christoph Doerbeck
##
## Summary:
##

---
- hosts: mySatellite, !myShelter
  tasks:

  - name: "SAT6-PREINSTALL-REPOS: disable all repos"
    shell:
      cmd: subscription-manager repos --disable="*"

  ##
  ## NOTE:  the with_items splits the comma separated list
  ##        of channels and prints a --enable=<val> for each
  ##        element.  Nice side effect is the the item
  ##        is output during execution
  ##

  - name: "SAT6-PREINSTALL-REPOS: enable needed repos"
    shell:
      cmd: subscription-manager repos {{ item }}
    with_items:
      - "{% for cv in sat6_assets[workshop_vars.satellite_version]['repos'].split(',') %} --enable={{ cv }}{% endfor %}"

  - name: "SAT6-PREINSTALL-REPOS: enable dnf satellite module for version = 6.12"
    shell:
      cmd: dnf module enable -y satellite:el8
    when: workshop_vars.satellite_version is version('6.12',operator='>=')
    
