
## Authors: 
##   Christoph Doerbeck
##
## Summary:
##

---
- hosts: mySatellite
  tasks:

  - debug: var=sat6_assets[g_satelliteVersion]['repos']

  - name: "SAT6-PREINSTALL-REPOS: enable repos"
    rhsm_repository: 
      name: "{{ sat6_assets[g_satelliteVersion]['repos'] }}"
      purge: True
      state: enabled
