
## Authors: 
##   Christoph Doerbeck
##
## Summary:
##

---
- hosts: mySatellite
  tasks:

  - name: "SAT6-PREINSTALL-REPOS: enable repos"
    rhsm_repository: 
      name: "{{ item }}"
      name: "rhel-7-server-rpms,rhel-7-server-satellite-6.6-rpms,rhel-7-server-satellite-maintenance-6-rpms,rhel-server-rhscl-7-rpms,rhel-7-server-ansible-2.8-rpms"
      purge: True
      state: enabled

