---
- hosts: mySatellite
  tasks:
  
    - name: "YUM install satellite packages"
      yum: name=satellite,sos,foreman-discovery-image state=installed

    - debug: var=sat6_assets[g_satelliteVersion]['install_cmd'] 

    - name: "CMD install satellite"
      shell: 
        cmd: |
          {{ sat6_assets[g_satelliteVersion]['install_cmd'] }}
