:gitrepo: https://github.com/xtophd/SAT6-Workshop
:includedir: _includes
:doctype: book
:sectnums:
:sectnumlevels: 3
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:imagesdir: ./_include/_images/

= Satellite 6: Workshop

[discrete]
== Presented By

  * Christoph Doerbeck

[discrete]
== Introduction

This guide is intended to support a series of workshop exercises for individuals getting familiar with Red Hat’s Satellite Server systems management platform.  

NOTE:  This whole effort is done using official Red Hat software and although things can probably be set up to work with upstream software components (CentOS, Pulp, CandlePin, Ansiblem, Puppet, etc...) I currently do not have the bandwidth to support the development and testing of alternate build environments.

[discrete]
== Conventions Used

[discrete]
=== Tips, Notes & Warnings

TIP: Extra info which could be helpful, but not essential for a given task or discussion

NOTE: Special information to pay attention

WARNING: Critical information which could help you avoid major set backs

[discrete]
=== Executing tasks on the CLI

[discrete]
==== Input

Each block of commands to execute will be labeled with the expected *user-id* and *host*.  To enhance cut & paste efficiency, the command prompt is omitted from each line.

.[root@master ~]#
----
systemctl status sshd
----

[discrete]
==== Output

Sample output will be titled with _'Your output should look like this'_ (or _'Command Output'_) and also be indented to help with visual identification.  Sometimes there will also be footnotes and/or callouts.

.Command Output
[source,indent=4]
----
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-02-26 12:04:16 EST; 27min ago // <1>
     Docs: man:sshd(8)
           man:sshd_config(5)
 Main PID: 3094 (sshd)
   CGroup: /system.slice/sshd.service
           └─3094 /usr/sbin/sshd -D
...<snip>...
----
<1> This is the line we are interested in with a special note

[discrete]
==== Alternate Commands

The workshop often provides cheat-scripts to ease certain complex tasks.  This helps the class stay focused and reduces the likelihood of errors and disruptions to the workshop delivery.  Honestly, we are not here to learn `vi`, `emacs` or start debates about the merits of `sed` and `awk`.

The native commands which the cheat-scripts utilize will be documented in the following way.

.[root@master ~]#
----
cheat-service-status.sh
----

[NOTE]
====
_Native command(s) to verify system service_
----
systemctl status sshd
----
====


[discrete]
== How to Connect

There are three options to complete the lab.

  . Follow the instructions to download the ssh-key and use a local terminal for the majority of exercises
  . Skip downloading the ssh-key and simply use a local terminal with credentials provided by your instructors
  . The last bullet of the LAB INFORMATION page, provides a link 'to consoles'.  By clicking that link, you can get true console access to "WORKSTATION".  

NOTE: you will need true console (GUI) on "WORKSTATION" for the *Wayland* and *Web Console* units.

[discrete]
== SAT 6 : EXERCISES

[#toc]
  . link:{includedir}/Getting-Started.adoc[*Workshop Preparation* - DO THIS FIRST!]
  . link:{includedir}/Common-Ops.adoc[*Common Operational Tasks*]
  . link:{includedir}/Content-Sync.adoc[*Content Synchronization*]
  . link:{includedir}/App-Lifecycles.adoc[*Application Lifecycles*]
  . link:{includedir}/Content-Views.adoc[*Content Views*]
  . link:{includedir}/Activation-Keys.adoc[*Activation Keys*]
  . link:{includedir}/Host-Management-Part1.adoc[*Host Management 1: Registration & Patching*]
  . link:{includedir}/Host-Management-Part2.adoc[*Host Management 2: Content Views & Life Cycles*]
  . link:{includedir}/Host-Management-Part3.adoc[*Host Management 3: Host Collections*]
  . link:{includedir}/Host-Management-Part4.adoc[*Host Management 4: Patching*]
  . link:{includedir}/Insights.adoc[*Insights*]
  . link:{includedir}/Host-Groups.adoc[*Host Groups*]
  . link:{includedir}/Discovery-Rules.adoc[*Discovery Rules*]
  . link:{includedir}/PXE-Discovery.adoc[*PXE Discovery*]
  . link:{includedir}/PXE-Less-Discovery.adoc[*PXE Less Discovery*]
  . link:{includedir}/Intro-Ansible.adoc[*Introduction to Ansible*]
  . link:{includedir}/Convert2RHEL.adoc[*Convert 2 RHEL*]
  . link:{includedir}/Scratch-Notes.txt[*Additional Scratch Notes*]

////  
TO PRINT THIS DOC REMOVE THIS LINE AND COMMENTS AROUND INCLUDES
include::{includedir}/Preface.adoc[leveloffset=+1]
include::{includedir}/Getting-Started.adoc[leveloffset=+1]
include::{includedir}/Common-Ops.adoc[leveloffset=+1]
include::{includedir}/Content-Sync.adoc[leveloffset=+1]
include::{includedir}/App-Lifecycles.adoc[leveloffset=+1]
include::{includedir}/Content-Views.adoc[leveloffset=+1]
include::{includedir}/Activation-Keys.adoc[leveloffset=+1]
include::{includedir}/Host-Management-Part1.adoc[leveloffset=+1]
include::{includedir}/Host-Management-Part2.adoc[leveloffset=+1]
include::{includedir}/Host-Management-Part3.adoc[leveloffset=+1]
include::{includedir}/Host-Management-Part4.adoc[leveloffset=+1]
include::{includedir}/Insights.adoc[leveloffset=+1]
include::{includedir}/Host-Groups.adoc[leveloffset=+1]
include::{includedir}/Discovery-Rules.adoc[leveloffset=+1]
include::{includedir}/PXE-Discovery.adoc[leveloffset=+1]
include::{includedir}/PXE-Less-Discovery.adoc[leveloffset=+1]
include::{includedir}/Intro-Ansible.adoc[leveloffset=+1]
include::{includedir}/Convert2RHEL.adoc[leveloffset=+1]
include::{includedir}/Scratch-Notes.txt[leveloffset=+1]
////


[discrete]
= The End

.Built-in
asciidoctor-version:: {asciidoctor-version}
safe-mode-name:: {safe-mode-name}

////
Always end files with a blank line to avoid include problems.
////
